---
dependencies: []

galaxy_info:
  author: geerlingguy
  description: ClamAV installation and configuration.
  company: "Midwestern Mac, LLC"
  license: "license (BSD, MIT)"
  min_ansible_version: 2.2
  platforms:
  - name: EL
    versions:
      - 6
      - 7
  - name: Ubuntu
    versions:
      - trusty
      - xenial
  - name: Debian
    versions:
      - jessie
      - stretch
  galaxy_tags:
    - networking
    - cloud
    - security
    - antivirus
    - antimalware
    - scan
