---
- import_tasks: set_vars.yaml
- name: install packages
  package:
    name: "{{ item}}"
    state: installed
  with_items:
    - "{{ telegraf_rpm_url }}"
    - ipmitool
    - lm_sensors

- name: configure ipmi permission 
  copy: 
    src: 52-telegraf-ipmo.rules 
    dest: /etc/udev/rules.d/52-telegraf-ipmi.rules 
    owner: root 
    group: root 
    mode: 0644

- name: apply ipmi conf
  shell: udevadm control --reload-rules && udevadm trigger



- name: create telegraf conf  
  template: 
    src: "{{telegraf_conf_src}}"
    dest: /etc/telegraf/telegraf.conf
    owner: root 
    group: root 
    mode: 0644

- name: restart_telegraf
  systemd: 
    name: telegraf 
    state: restarted 
    enabled: yes 
    daemon_reload: yes

- name: add firewalld rules
  firewalld:
    zone: public
    port: 9273/tcp
    permanent: true
    state: enabled
  when: ansible_os_family == "RedHat"

- name: reload firewalld
  shell: firewall-cmd --reload  
  when: ansible_os_family == "RedHat"
  