---
- import_tasks: set_vars.yaml

- name: add repo on RHEL/CentOS
  yum_repository:
    name: InfluxDB Repository - RHEL \$releasever
    description: InfluxDB Repository 
    baseurl: https://repos.influxdata.com/rhel/\$releasever/\$basearch/stable
    enabled: yes
    gpgcheck: yes
    gpgkey: https://repos.influxdata.com/influxdb.key
  when: ansible_os_family == "RedHat"  

- name: install depenency packages
  package:
    name: "{{ item}}"
    state: installed
  with_items:
    - ipmitool
    - lm_sensors
  when: ansible_os_family == "RedHat"  

- name: install depenency packages
  package:
    name: "{{ item}}"
    state: installed
  with_items:
    - ipmitool
    - sensors
  when: ansible_os_family == "Suse"  
  

- name: install  telegraf packages on RHEL/CentOS
  package:
    name: telegraf
    state: latest
  when: ansible_os_family == "RedHat" 


- name: install  telegraf packages on Suse
  package:
    name: telegraf
    state: latest
    skip_broken: yes
  when: ansible_os_family == "RedHat" 
  

- name: configure ipmi permission 
  copy: 
    src: 52-telegraf-ipmo.rules 
    dest: /etc/udev/rules.d/52-telegraf-ipmi.rules 
    owner: root 
    group: root 
    mode: 0644

- name: apply ipmi conf
  shell: udevadm control --reload-rules && udevadm trigger

- name: create telegraf conf  
  template: 
    src: "{{telegraf_conf_src}}"
    dest: /etc/telegraf/telegraf.conf
    owner: root 
    group: root 
    mode: 0644
  register: telegraf_conf

- name: install telegraf.service
  copy: 
    src: telegraf.service
    dest: /usr/lib/systemd/system/telegraf.service
  register: telegraf_service

- name: restart_telegraf
  systemd: 
    name: telegraf 
    state: restarted 
    enabled: yes 
    daemon_reload: yes
  when: telegraf_conf is changed or telegraf_service is changed

- name: add firewalld rules
  firewalld:
    zone: public
    port: 9273/tcp
    permanent: true
    state: enabled
  when: ansible_os_family == "RedHat"

- name: reload firewalld
  shell: firewall-cmd --reload  
  when: ansible_os_family == "RedHat"
  