- name: clear prvious conf if exists
  shell: rm -rf /etc/logstash/arcsight
  args:
    warn: no
- name: create required directory
  shell: mkdir -p /etc/logstash/arcsight/{conf.d,definitions,dictionaries,geoipdbs,templates}
  args:
    warn: no
    executable: /bin/bash

- name: create cef input and fileter conf
  copy:
    src: "{{cef_conf}}"
    dest: /etc/logstash/cef/conf.d/
  with_fileglob:
  - "{{role_path}}/files/arcsight*.conf"
  loop_control:
    loop_var: cef_conf

- name: create cef output conf
  template:
    src: arcsight-output.conf.j2
    dest: /etc/logstash/cef/conf.d/arcsight-output.conf