- name: clear prvious conf if exists
  shell: rm -rf /etc/logstash/arcsight
  args:
    warn: no
- name: create required directory
  shell: mkdir -p /etc/logstash/arcsight/{conf.d,definitions,dictionaries,geoipdbs,templates}
  args:
    warn: no
    executable: /bin/bash

- name: create cef input and fileter conf
  copy:
    src: "{{cef_conf}}"
    dest: /etc/logstash/arcsight/conf.d/
  with_fileglob:
  - "{{role_path}}/files/arcsight*.conf"
  loop_control:
    loop_var: cef_conf

- name: create cef output conf
  template:
    src: arcsight-output.conf.j2
    dest: /etc/logstash/arcsight/conf.d/arcsight-output.conf



- name: set up index for arcsight on kibana
  uri:
    url: "{{KIBABA_SCHEMA}}://{{KIBANA_INSTANCE}}/api/saved_objects/index-pattern/arcsight-*"
    method: POST
    src: /usr/share/logstash/x-pack/modules/arcsight/configuration/kibana/6.x/index-pattern/arcsight.json
    user: "{{KIBANA_USER}}"
    password: "{{KIBANA_PASS}}"
    force_basic_auth: yes
    headers:
        Content-Type: "application/json"
        kbn-xsrf: true
  ignore_errors: yes

- name: import elastiflow dashboard
  uri:
    url: "{{KIBABA_SCHEMA}}://{{KIBANA_INSTANCE}}/api/kibana/dashboards/import"
    method: POST
    src:  "{{dashboard}}"
    user: "{{KIBANA_USER}}"
    password: "{{KIBANA_PASS}}"
    force_basic_auth: yes
    headers:
        Content-Type: "application/json"
        kbn-xsrf: true
  with_fileglob:
  - /usr/share/logstash/x-pack/modules/arcsight/configuration/kibana/6.x/dashboard/*
  loop_control:
    loop_var: dashboard
  ignore_errors: yes
