- name: create required directory
  shell: mkdir -p /etc/logstash/cef/{conf.d,definitions,dictionaries,geoipdbs,templates}
  args:
    warn: no
    executable: /bin/bash

- name: create cef input and fileter conf
  copy:
    src: "{{cef_conf}}"
    dest: /etc/logstash/cef/conf.d/
  with_fileglob:
  - "{{role_path}}/files/cef*.conf"
  loop_control:
    loop_var: cef_conf

- name: create cef output conf
  template:
    src: cef-output.conf.j2
    dest: /etc/logstash/cef/conf.d/