- name: add logstash repo
  yum_repository:
    name: logstash-6.x
    description: Elastic repository for 6.x packages
    baseurl: https://artifacts.elastic.co/packages/6.x/yum
    gpgcheck: 1
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: 1
  when: ansible_os_family == "RedHat" or ansible_os_family == "Suse"

- name: Add logstash apt key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    keyring: /etc/apt/trusted.gpg.d/elasticsearch.gpg
  when: ansible_os_family == "Debian"

- name: add logstash repo
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/6.x/apt stable main
    state: present
    filename: elastic-6.x
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: ensure logstash is installed
  package:
    name: "logstash"
    state: present

- name: install other tools
  package:
    name: "{{item}}"
    state: present
  with_items:
  - unzip 
  - curl



- name: include tasks for each enabled pipeline
  include_tasks: "{{ pipeline.id }}.yml"
  with_items:
  - "{{ LOGSTASH_ENABLED_PIPELINES }}"
  loop_control:
    loop_var: pipeline

- name: create pipelines.yml
  template:
    src: pipelines.yml.j2
    dest: /etc/logstash/pipelines.yml

- name: create /etc/logstash/logstash.yml
  template:
    src: logstash.yml.j2
    dest: /etc/logstash/logstash.yml

- name: configure JVM heap (1)
  lineinfile:
      path: /etc/logstash/jvm.options  
      regexp: '^-Xms\\d+g$' 
      line: '-Xms4g'
      create: yes

- name: configure JVM heap (2)
  lineinfile:
      path: /etc/logstash/jvm.options  
      regexp: '^-Xmx\\d+g$' 
      line: '-Xmx4g'    
- name:  configure pipelines
  template:
      src: pipelines.yml.j2
      dest: /etc/logstash/pipelines.yml  

- name: restart logstash 
  systemd:
    name: logstash
    state: restarted
    daemon_reload: yes    