- name: add logstash repo
  yum_repository:
    name: logstash-6.x
    description: Elastic repository for 6.x packages
    baseurl: https://artifacts.elastic.co/packages/6.x/yum
    gpgcheck: 1
    gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    enabled: 1
  when: ansible_os_family == "RedHat" or ansible_os_family == "Suse"

- name: add logstash repo
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/6.x/apt stable main
    state: present
    filename: elastic-6.x
  when: ansible_os_family == "Debian"

- name: Add an apt logstash  
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
  when: ansible_os_family == "Debian"

- name: ensure logstash is installed
  yum:
    name: "logstash-{{LOGSTAASH_VERSION}}"
    state: present
  when: ansible_os_family == "RedHat" or ansible_os_family == "Suse"

- name: ensure logstash is installed
  yum:
    name: "logstash={{LOGSTAASH_VERSION}}"
    state: present
  when: ansible_os_family == "Debian"

- name: install dependencies
  package:
    name: "{{item}}"
    state: installed
  with_items:
  - unzip 
  - curl

- import_tasks: elastiflow.yml 