
telegraf_rpm_version: 1.5.2 
telegraf_rpm_url: https://dl.influxdata.com/telegraf/releases/telegraf-{{ telegraf_rpm_version }}-1.x86_64.rpm
telegraf_mon_process: true
telegraf_mon_processes:
  - master
  - clamd