---
- name: check hana_exporter existence and version
  shell: /usr/bin/hana_exporter  --version >/dev/stdout 2>&1 |grep hana_exporter|awk '{print $3}'|grep {{ hana_exporter_version }}
  register: hana_exporter
  ignore_errors: yes

- name: Define hana_exporter_package_url
  set_fact:
    hana_exporter_package_url: "{{ hana_exporter_rpm_url }}"
  when: ansible_os_family == 'RedHat'

- name: Define hana_exporter_package_url
  set_fact:
    hana_exporter_package_url: "{{ hana_exporter_deb_url }}"
  when: ansible_os_family == 'Debian'

- name: install hana_exporter
  package:
    name: "{{ hana_exporter_package_url }}"
    state: present
  when: hana_exporter.rc  != 0 



- name: create hana_exporter conf 
  template:
    src: hana_exporter.yml.j2
    dest: /etc/hana_exporter/hana_exporter.yml
    mode: 0755
    owner: hana_exporter
    group: prometheus
  notify: 
    restart_hana_exporter
  
- name: restart hana_exporter service
  systemd: 
    name:  hana_exporter 
    state:  restarted 
    enabled:  yes
    daemon_reload:  yes

