---

- name: Define hana_exporter_package_url
  set_fact:
    hana_exporter_package_url: "{{ hana_exporter_rpm_url }}"
  when: ansible_os_family == 'RedHat'

- name: Define hana_exporter_package_url
  set_fact:
    hana_exporter_package_url: "{{ hana_exporter_deb_url }}"
  when: ansible_os_family == 'Debian'

- name: install hana_exporter
  package:
    name: "{{ hana_exporter_package_url }}"
    state: present



- name: create hana_exporter conf 
  template:
    src: hana_exporter.yml.j2
    dest: /etc/hana_exporter/hana_exporter.yml
    mode: 0755
    owner: hana_exporter
    group: prometheus
  register: hana_exporter_conf
  
- name: restart hana_exporter service
  systemd: 
    name:  hana_exporter 
    state:  restarted 
    enabled:  yes
    daemon_reload:  yes
  when: hana_exporter_conf is changed

