- name: ensure postfix and related packages are installed 
  package:
    name: "{{item}}"
    state: installed
  with_items:
    - postfix
    - cyrus-sasl-plain
    - cyrus-sasl

- name: install relay credential
  copy: 
    src: relay_credential
    dest: /etc/postfix/relay_credential

    
- name: convert post map
  shell: postmap /etc/postfix/relay_credential

- name: install mail fromAddr aliase
  copy:
    src: generic
    dest: /etc/postfix/generic  

- name: covert mail fromAddre to postmap
  shell: postmap /etc/postfix/generic

- name: install postfix main conf
  copy: 
    src: main.cf
    dest:  /etc/postfix/main.cf 

- name: restart postfix
  systemd: 
    name: postfix
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: add firewalld rules
  firewalld:
    zone: public
    service: postfix 
    permanent: true
    state: enabled
  when: ansible_os_family == "RedHat" 

 - name: reload firewalld
   shell: firewalld-cmd --reload
  when: ansible_os_family == "RedHat" 
