- name: download cisco mibs 
  unarchive:
    src:  ftp://ftp.cisco.com/pub/mibs/v2/v2.tar.gz
    dest: /usr/share/snmp/mibs/cisco
    remote_src: yes

- name: download f5 mibs
  unarchive:
    src: https://{{BIGIP_IP}}/docs/mibs/mibs_f5.tar.gz
    dest: /usr/share/snmp/mibs/f5
    remote_src: yes
    validate_certs: no


- name: download lenovo mibs
  unarchive:
    src: 
    - https://download.lenovo.com/servers/mig/2018/07/18/19010/lnvgy_fw_xcc_cdi324q-1.90_lenovoxcc-anyos_noarch.mib
    - https://download.lenovo.com/servers/mig/2018/07/18/19010/lnvgy_fw_xcc_cdi324q-1.90_lenovosmi-anyos_noarch.mib
    dest: /usr/share/snmp/mibs/lenovo
    remote_src: yes
    
- name: download paloalto mibs 
  unarchive:
    src:  https://www.paloaltonetworks.com/content/dam/pan/en_US/assets/zip/technical-documentation/snmp-mib-modules/PAN-MIB-MODULES-7.0.zip
    dest: /usr/share/snmp/mibs/paloalto
    remote_src: yes

- name: add mib path to /etc/snmp/snmp.conf
  



- name: check snmp_export
  shell: /usr/bin/snmp_export  --version |grep -i snmp_exporter |grep {{ snmp_exporter_version }}
  register: snmp_export
  ignore_errors: yes

- name: download snmp_exporter

- name: download telegraf binary 
  get_url:
    url: "{{ snmp_exporter_binary_url}}"
    dest: "/tmp/snmp_exporter-{{snmp_exporter_version}}.linux-amd64.tar.gz"
  when:  snmp_export.rc  != 0
  
- name: Unarchive  snmp_exporter binary 
  unarchive:
    src: "/tmp/snmp_exporter-{{snmp_exporter_version}}.linux-amd64.tar.gz"
    dest: /tmp
    remote_src: yes
  when: snmp_export.rc  != 0

- name: copy snmp_exporter binary
  copy:
    src: /tmp/snmp_exporter-{{snmp_exporter_version}}.linux-amd64/snmp_exporter"
    dest: /usr/bin
    remote_src: yes
    mode: 0755

- name: create snmp_exporter conf dir
  file:
    path: /etc/snmp_exporter/
    state: directory
    mode: 0755 

- name: copy snmp_exporter conf
  copy:
    src: /tmp/snmp_exporter-{{snmp_exporter_version}}.linux-amd64/snmp.yml"
    dest: /etc/snmp_exporter/
    remote_src: yes
    mode: 0644

- name: create snmp_exporter service file
  template:
    src: snmp_exporter.service
    dest: /lib/systemd/system/snmp_exporter.service
    
- name: start snmp_exporter 
  systemd: 
    name: snmp_exporter 
    state: restarted 
    enabled: yes
    daemon_reload: yes
    