
prometheus_ext_url: 
alertmanager_addrs:
prometheus_storage_tsdb_path: 
prometheus_storage_tsdb_retention:

prometheus_file_sd_job_list:
- { 'job_name': 'prometheus', 'metrics_path': '/metrics' }
- { 'job_name': 'alertmanager', 'metrics_path': '/metrics' }
- { 'job_name': 'grafana', 'metrics_path': '/metrics'}
- { 'job_name': 'telegraf', 'metrics_path': '/metrics'}
- { 'job_name': 'mysql_exporter', 'metrics_path': '/metrics'}
- { 'job_name': 'hana_exporter', 'metrics_path': '/hana','hana_exporter_addr': '192.168.0.1:9460' }
- { 'job_name': 'blackbox_exporter', 'metrics_path': '/probe','blackbox_exporter_addr':'192.168.0.1:9115'}
- { 'job_name': 'snmp_exporter', 'metrics_path': '/snmp','snmp_exporter_addr':'192.168.0.1:9116' }
- { 'job_name': 'ipmi_exporter', 'metrics_path': '/ipmi','ipmi_exporter_addr':'192.168.0.1:9290' }
- { 'job_name': 'bigpip_exporter', 'metrics_path': '/bigip','bigpip_exporter_addr':'192.168.0.1:9142' }

- { 'job_name': 'nginx_exporter', 'metrics_path': '/metrics'}
- { 'job_name': 'netapp-harvest', 'metrics_path': '/metrics'}

prometheus_consul_sd_job_list:
- { 'job_name': 'ipmi_exporter', 'metrics_path': '/ipmi','target_meta': {'type': 'proxy','proxy_type': 'ipmi_exporter','proxy_addr': 'localhost:9290'},'consule_server': 'localhost:8500','consule_datacenter': 'dc1','consule_service': 'ipmi_exporter'}
- { 'job_name': 'bigip_exporter', 'metrics_path': '/bigip','target_meta': {'type': 'proxy','proxy_type': 'bigip_exporter','proxy_addr': 'localhost:9142'},'consule_server': 'localhost:8500','consule_datacenter': 'dc1','consule_service': 'bigip_exporter'}

- { 'job_name': 'snmp_exporter', 'metrics_path': '/snmp','target_meta': {'type':' proxy','proxy_type': 'snmp_exporter','proxy_addr': 'localhost:9116','module': 'xcc'},'consule_server': 'localhost:8500','consule_datacenter': 'dc1','consule_service': 'snmp_exporter'}
- { 'job_name': 'hana_exporter', 'metrics_path': '/hana','target_meta': {'type':' proxy','proxy_type': 'hana_exporter','proxy_addr': 'localhost:9460'},'consule_server': 'localhost:8500','consule_datacenter': 'dc1','consule_service': 'hana_exporter'}
- { 'job_name': 'blackbox_exporter', 'metrics_path': '/probe','target_meta': {'type':'proxy','proxy_type': 'blackbox_exporter','proxy_addr': 'localhost:9115','module': 'http_2xx'},'consule_server': 'localhost:8500','consule_datacenter': 'dc1','consule_service': 'blackbox_exporter'}
- { 'job_name': 'prometheus', 'metrics_path': '/metrics','target_meta':{'type': 'direct'},'consule_server': 'localhost:8500','consule_datacenter': 'dc1','consule_service': 'prometheus'}
- { 'job_name': 'alertmanager', 'metrics_path': '/metrics','target_meta':{'type': 'direct'},'consule_server': 'localhost:8500','consule_datacenter': 'dc1','consule_service': 'alertmanager'}
- { 'job_name': 'grafana', 'metrics_path': '/metrics','target_meta':{'type': 'direct'},'consule_server': 'localhost:8500','consule_datacenter': 'dc1','consule_service': 'grafana'}
- { 'job_name': 'telegraf', 'metrics_path': '/metrics','target_meta':{'type': 'direct'},'consule_server': 'localhost:8500','consule_datacenter': 'dc1','consule_service': 'telegraf'}
- { 'job_name': 'mysql_exporter', 'metrics_path': '/metrics','target_meta': {'type': 'direct'},'consule_server': 'localhost:8500','consule_datacenter': 'dc1','consule_service': 'mysql_exporter'}
- { 'job_name': 'nginx_exporter', 'metrics_path': '/metrics','target_meta': {'type': 'direct'},'consule_server': 'localhost:8500','consule_datacenter': 'dc1','consule_service': 'nginx_exporter'}
- { 'job_name': 'netapp-harvest', 'metrics_path': '/metrics','target_meta': {'type': 'direct'},'consule_server': 'localhost:8500','consule_datacenter': 'dc1','consule_service': 'netapp-harvest'}



prometheus_file_sd_alertmanager_list:
- /etc/prometheus/alertmanagers.yml

prometheus_consul_sd_alertmanager_list:
- {'consule_server': 'localhost:8500','consule_datacenter': 'dc1','consule_service': 'alertmanager'}
