
prometheus_ext_url: 
alertmanager_addrs:
prometheus_storage_tsdb_path: 
prometheus_storage_tsdb_retention:

prometheus_file_sd_job_list:
- { 'job_name': 'prometheus', 'metrics_path': '/metrics'}
- { 'job_name': 'alertmanager', 'metrics_path': '/metrics'}
- { 'job_name': 'grafana', 'metrics_path': '/metrics'}
- { 'job_name': 'telegraf', 'metrics_path': '/metrics'}
- { 'job_name': 'mysql', 'metrics_path': '/metrics'}
- { 'job_name': 'hana', 'metrics_path': '/hana','hana_exporter_host': '192.168.0.1'}
- { 'job_name': 'blackbox', 'metrics_path': '/probe','blackbox_exporter_host':'192.168.0.1'}
- { 'job_name': 'nginx', 'metrics_path': '/metrics'}
- { 'job_name': 'vcenter', 'metrics_path': '/metrics'}
- { 'job_name': 'netapp-harvest', 'metrics_path': '/metrics'}


prometheus_consul_sd_job_list:
- { 'job_name': 'prometheus', 'metrics_path': '/metrics','target_meta':{'type':'direct'},'consule_server': 'localhost:8500','consule_datacenter': 'dc1','consule_service': 'prometheus'}
- { 'job_name': 'ipmi_exporter', 'metrics_path': '/ipmi','target_meta':{'type':'proxy','proxy_type':'ipmi_exporter','proxy_addr':'localhost:9290'},'consule_server': 'localhost:8500','consule_datacenter': 'dc1','consule_service': 'ipmi_exporter'}
- { 'job_name': 'snmp_exporter', 'metrics_path': '/ipmi','target_meta':{'type':'proxy','proxy_type':'snmp_exporter','proxy_addr':'localhost:9116','snmp_module':'xcc'},'consule_server': 'localhost:8500','consule_datacenter': 'dc1','consule_service': 'snmp_exporter'}
- { 'job_name': 'snmp_exporter', 'metrics_path': '/bigip','target_meta':{'type':'proxy','proxy_type':'bigip_exporter','proxy_addr':'localhost:9142'},'consule_server': 'localhost:8500','consule_datacenter': 'dc1','consule_service': 'bigip_exporter'}

prometheus_file_sd_alertmanager_list:
- /etc/prometheus/alertmanagers.yml

prometheus_consul_sd_alertmanager_list:
- {'consule_server': 'localhost:8500','consule_datacenter': 'dc1','consule_service': 'alertmanager'}
