
prometheus_ext_url: 
alertmanager_addrs:
prometheus_storage_tsdb_path: 
prometheus_storage_tsdb_retention:

prometheus_file_sd_job_list:
- { 'job_name': 'prometheus', 'metrics_path': '/metrics'}
- { 'job_name': 'alertmanager', 'metrics_path': '/metrics'}
- { 'job_name': 'grafana', 'metrics_path': '/metrics'}
- { 'job_name': 'telegraf', 'metrics_path': '/metrics'}
- { 'job_name': 'mysql', 'metrics_path': '/metrics'}
- { 'job_name': 'hana', 'metrics_path': '/hana','hana_exporter_host': '192.168.0.1'}
- { 'job_name': 'blackbox', 'metrics_path': '/probe','blackbox_exporter_host':'192.168.0.1'}
- { 'job_name': 'nginx', 'metrics_path': '/metrics'}
- { 'job_name': 'vcenter', 'metrics_path': '/metrics'}
- { 'job_name': 'netapp-harvest', 'metrics_path': '/metrics'}


prometheus_consul_sd_job_list:
- { 'job_name': 'prometheus', 'metrics_path': '/metrics','consule_server': 'localhost:8500','consule_token': 'dfslfk','consule_datacenter': 'sc','consule_services': ['service1','service2'],'tag': 'prometheus','consule_node_meta': {'key1': 'value1','key2': 'value2'},'consule_allow_stale': 'true','refresh_interval': '10s'}

prometheus_file_sd_alertmanager_list:
- /etc/prometheus/alertmanagers.yml

prometheus_consul_sd_alertmanager_list:
- {'consule_server': 'localhost:8500','consule_token': 'dfslfk','consule_datacenter': 'sc','consule_services': ['service1','service2'],'tag': 'alertmanager','consule_node_meta': {'key1': 'value1','key2': 'value2'},'consule_allow_stale': 'true','refresh_interval': '10s'}
