- name: check if bigip_exporter is installed and its version 
  shell: bigip_exporter --version>/dev/stdout 2>&1|grep bigip_exporter | grep "{{bigip_exporter_version}}"
  register: bigip_exporter
  ignore_errors: yes

  
- name: download bigip_exporter binary 
  get_url:
    url: "{{ bigip_exporter_binary_url}}"
    dest: "/tmp/bigip_exporter-{{bigip_exporter_version}}.linux-amd64.tar.gz"
  when:  bigip_exporter.rc  != 0

- name: Unarchive bigip binary 
  unarchive:
    src: "/tmp/bigip_exporter-{{bigip_exporter_version}}.linux-amd64.tar.gz"
    dest: /tmp
    remote_src: yes
  when:  bigip_exporter.rc  != 0
  
- name: create bigip_exporter conf dir
  file:
    path: /etc/prometheus/
    state: directory
    mode: 0755

- name: stop bigip_exporter if possible
  systemd:
    name: bigip_exporter
    state: stopped
  when: bigip_exporter.rc  != 0
- name: copy bigip_exporter binary
  copy:
    src: "/tmp/bigip_exporter-{{bigip_exporter_version}}.linux-amd64/bigip_exporter"
    dest: /usr/bin
    remote_src: yes
    mode: 0755
  when:  bigip_exporter.rc  != 0

- name: create bigip_exporter service file
  copy:
    src: bigip_exporter.service
    dest: /lib/systemd/system/bigip_exporter.service
  register: bigip_exporter_service


- name: create bigip_exporter conf file 
  template:
    src: bigip_exporter.yml.j2
    dest: /etc/prometheus/bigip_exporter.yml
  register: bigip_exporter_conf

- name: restart bigip_exporter 
  systemd: 
    name: bigip_exporter 
    state: restarted 
    enabled: yes
    daemon_reload: yes
  when: bigip_exporter_service is changed or bigip_exporter_conf is changed
- name: add firewalld rules
  firewalld:
    zone: public
    port: 9142/tcp
    permanent: true
    state: enabled
- name: reload firewalld
  shell: firewall-cmd --reload    
    