groups:
- name: Basic alerts
  rules:
  - alert: High CPU usage (warning)
    expr: cpu_usage_idle{cpu="cpu-total"} < 70
    for: 5m
    labels:
      severity: warning
    annotations:
      description: '{{$labels.host}}({{$labels.instance}}): has really high CPU usage for over 5m ,current system idle is: {{ $value }} .'
      summary: 'High CPU Usage detected!'
  - alert: High CPU usage (critical)
    expr: cpu_usage_idle{cpu="cpu-total"} < 60
    for: 5m
    labels:
      severity: critical
    annotations:
      description: '{{$labels.host}}({{$labels.instance}}): has really high CPU usage for over 5m, current system idle is: {{ $value }} .'
      summary: 'High CPU Usage detected!'
  - alert: High Disk Usage (warning)
    expr: disk_used_percent{fstype =~ "(xfs|ext3)" }  > 85
    for: 5m
    labels:
      severity: warning
    annotations:
      description: '{{$labels.host}}({{$labels.instance}}): Mount Point {{ $labels.path}}  is used above 85%,current value is: {{ $value }} .'
      summary: 'Low data disk space detected'
  - alert: High Disk Usage (critical)
    expr: disk_used_percent {fstype =~ "(xfs|ext3)" } > 90
    for: 5m
    labels:
      severity: critical
    annotations:
      description: '{{$labels.host}}({{$labels.instance}}): Mount Point {{ $labels.path}}  is used above 90%,current value is: {{ $value }} .'
      summary: 'Low data disk space detected'
  - alert: High Memory usage (warning)
    expr: mem_used_percent > 85
    for: 2m
    labels:
      severity: warning
    annotations:
      description: '{{$labels.host}}({{$labels.instance}}): Memory usage is above 75%current value is: {{ $value }} .'
      summary: 'High memory usage detected'

  - alert: High Memory usage (critical)
    expr: mem_used_percent > 90
    for: 2m
    labels:
      severity: critical
    annotations:
      description: '{{$labels.host}}({{$labels.instance}}): Memory usage is above 90%，current value is: {{ $value }} .'
      summary: 'High memory usage detected'

  - alert: High node Load Average (warning)
    expr: system_load5 > 0.7 * system_n_cpus
    for: 2m
    labels:
      severity: warning
    annotations:
      description: '{{$labels.host}}({{$labels.instance}}): Average Load is high,current value is: {{ $value }} .'
      summary: 'High Average Load detected'
  - alert: High node Load Average (critical)
    expr: system_load5 > system_n_cpus
    for: 2m
    labels:
      severity: critical
    annotations:
      description: '{{$labels.host}}({{$labels.instance}}): Average Load is high,current value is: {{ $value }} .'
      summary: 'High Average Load detected'

  - alert: High Swap Usage (warning)
    expr: swap_used_percent > 50
    for: 2m
    labels:
      severity: warning
    annotations:
      description: '{{$labels.host}}({{$labels.instance}}): Swap usage usage is above 50%,current value is: {{ $value }} .'
      summary: 'High Swap usage detected'
  - alert: High Swap Usage (critical)
    expr: swap_used_percent > 75
    for: 2m
    labels:
      severity: critical
    annotations:
      description: '{{$labels.host}}({{$labels.instance}}): Swap usage usage is above 75%,current value is: {{ $value }} .'
  - alert: Instance is Down
    expr: up == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      description: '{{$labels.instance}} of job {{$labels.job}} has been down for  more than 2 minutes.'
      summary: Instance down
  - alert: Preditcive Host Disk Space Hign
    expr: predict_linear(disk_used_percent{fstype =~ "(xfs|ext3)"}[4h], 4*3600) > 98
    for: 2m
    labels:
      severity: critical
    annotations:
      description: 'Based on recent sampling, the disk is likely to will fill on volume {{ $labels.path }} within the next 4 hours for instace: {{ $labels.instance }}.'
      summary: 'Predictive Disk Space Utilisation Alert'
  - alert: Preditcive Host CPU Usage High
    expr: predict_linear(cpu_usage_idle{cpu="cpu-total"}[4h], 4*3600) < 40
    for: 2m
    labels:
      severity: critical
    annotations:
      description: 'Based on recent sampling, the CPU usage is increase incredible high  within the next 4 hours for instace: {{ $labels.instance }}.'
      summary: 'Predictive Host CPU usage  Alert'
  - alert: Preditcive Host Memory Usage  High
    expr: predict_linear(mem_used_percent{cpu="cpu-total"}[4h], 4*3600) > 90
    for: 2m
    labels:
      severity: critical
    annotations:
      description: 'Based on recent sampling, the Memory usage is increase incredible high  within the next 4 hours for instace: {{ $labels.instance }}.'
      summary: 'Predictive Host Memory usage  Alert'
      
- name: HANA alerts
  rules:
  - alert: HANA process hdbwebdispatcher is not running
    expr: absent(procstat_pid{instance="10.36.50.13",process_name  = "hdbwebdispatcher"}) == 1
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'process {{$labels.process_name}} on host 10.36.50.13 is not running  for over 5m.'
      summary: 'HANA process hdbwebdispatcher is not running!'
  - alert: HANA process hdbnameserver is not running
    expr: absent(procstat_pid{instance="10.36.50.13",process_name  = "hdbnameserver"}) == 1
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'process {{$labels.process_name}} on host 10.36.50.13 is not running  for over 5m.'
      summary: 'HANA process hdbnameserver is not running!'
  - alert: HANA process hdbcompileserver is not running
    expr: absent(procstat_pid{instance="10.36.50.13",process_name  = "hdbcompileserver"})  == 1
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'process {{$labels.process_name}} on host 10.36.50.13 is not running  for over 5m.'
      summary: 'HANA process hdbcompileserver is not running!'
  - alert: HANA process hdbpreprocessor is not running
    expr: absent(procstat_pid{instance="10.36.50.13",process_name  = "hdbpreprocessor"}) == 1
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'process {{$labels.process_name}} on host 10.36.50.13 is not running  for over 5m.'
      summary: 'HANA process hdbpreprocessor is not running!'
  - alert: HANA process hdbindexserver is not running
    expr: absent(procstat_pid{instance="10.36.50.13",process_name  = "hdbindexserver"}) == 1
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'process {{$labels.process_name}} on host 10.36.50.13 is not running  for over 5m .'
      summary: 'HANA process hdbindexserver is not running!'
  - alert: HANA process hdbxsengine is not running
    expr: absent(procstat_pid{instance="10.36.50.13",process_name  = "hdbxsengine"}) == 1
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'process {{$labels.process_name}} on host 10.36.50.13 is not running  for over 5m.'
      summary: 'HANA process hdbxsengine is not running!'



  - alert: HANA process hdbwebdispatcher is not running
    expr: absent(procstat_pid{instance="10.36.50.141",process_name  = "hdbwebdispatcher"}) == 1
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'process {{$labels.process_name}} on host 10.36.50.141 is not running  for over 5m.'
      summary: 'HANA process hdbwebdispatcher is not running!'
  - alert: HANA process hdbnameserver is not running
    expr: absent(procstat_pid{instance="10.36.50.141",process_name  = "hdbnameserver"}) == 1
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'process {{$labels.process_name}} on host 10.36.50.141 is not running  for over 5m.'
      summary: 'HANA process hdbnameserver is not running!'
  - alert: HANA process hdbcompileserver is not running
    expr: absent(procstat_pid{instance="10.36.50.141",process_name  = "hdbcompileserver"})  == 1
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'process {{$labels.process_name}} on host 10.36.50.141 is not running  for over 5m.'
      summary: 'HANA process hdbcompileserver is not running!'
  - alert: HANA process hdbpreprocessor is not running
    expr: absent(procstat_pid{instance="10.36.50.141",process_name  = "hdbpreprocessor"}) == 1
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'process {{$labels.process_name}} on host 10.36.50.141 is not running  for over 5m.'
      summary: 'HANA process hdbpreprocessor is not running!'
  - alert: HANA process hdbindexserver is not running
    expr: absent(procstat_pid{instance="10.36.50.141",process_name  = "hdbindexserver"}) == 1
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'process {{$labels.process_name}} on host 10.36.50.141 is not running  for over 5m.'
      summary: 'HANA process hdbindexserver is not running!'
  - alert: HANA process hdbxsengine is not running
    expr: absent(procstat_pid{instance="10.36.50.141",process_name  = "hdbxsengine"}) == 1
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'process {{$labels.process_name}} on host 10.36.50.141 is not running  for over 5m.'
      summary: 'HANA process hdbxsengine is not running!'


  - alert: HANA Cluster sbd process is not running
    expr: absent(procstat_pid{instance="10.36.50.13",process_name = "sbd"})  == 1
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'process {{$labels.process_name}} on host 10.36.50.13 is not running  for over 5m.'
      summary: 'HANA Cluster sbd process is not running'

  - alert: HANA Cluster corosync process is not running
    expr: absent(procstat_pid{instance="10.36.50.13",process_name = "corosync"})  == 1
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'process {{$labels.process_name}} on host 10.36.50.13 is not running  for over 5m.'
      summary: 'HANA Cluster corosync process is not running'

  - alert: HANA Cluster cib process is not running
    expr: absent(procstat_pid{instance="10.36.50.13",process_name = "cib"})  == 1
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'process {{$labels.process_name}} on host 10.36.50.13 is not running  for over 5m.'
      summary: 'HANA Cluster cib process is not running'
  - alert: HANA Cluster attrd process is not running
    expr: absent(procstat_pid{instance="10.36.50.13",process_name = "attrd"})  == 1
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'process {{$labels.process_name}} on host 10.36.50.13 is not running  for over 5m.'
      summary: 'HANA Cluster attrd process is not running'
  - alert: HANA Cluster pengine process is not running
    expr: absent(procstat_pid{instance="10.36.50.13",process_name = "pengine"})  == 1
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'process {{$labels.process_name}} on host 10.36.50.13 is not running  for over 5m.'
      summary: 'HANA Cluster pengine process is not running'
  - alert: HANA Cluster crmd process is not running
    expr: absent(procstat_pid{instance="10.36.50.13",process_name = "crmd"})  == 1
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'process {{$labels.process_name}} on host 10.36.50.13 is not running  for over 5m.'
      summary: 'HANA Cluster crmd process is not running'

  - alert: HANA Port is not listening
    expr: net_response_response_time{result_type !="success",instance=~"(10.36.50.13|10.36.50.141)"}  >= 1
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'Port {{$labels.port}} on host {{$labels.host}}({{$labels.instance}}) is not listening  for over 5m  {{ $value }} .'
      summary: 'High CPU Usage detected!'

- name: Service alerts
  rules:
  - alert: grafana-server process is not running
    expr: absent(procstat_pid{job="grafana",process_name = "grafana-server"})  == 1
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'process {{$labels.process_name}} on host {{$labels.instance}}  is not running  for over 5m.'
      summary: 'grafana-server process is not running'
  - alert: logstash process is not running
    expr: absent(procstat_pid{job="logstash",pattern = "logstash"})  == 1
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'process {{$labels.process_name}} on host {{$labels.instance}}  is not running  for over 5m.'
      summary: 'logstash process is not running'          
  - alert: kibana process is not running
    expr: absent(procstat_pid{job="kibana",pattern = "kibana"})  == 1
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'process {{$labels.process_name}} on host {{$labels.instance}}  is not running  for over 5m.'
      summary: 'kibana process is not running'            
  - alert: elasticsearch process is not running
    expr: absent(procstat_pid{job="es",pattern = "elasticsearch"})  == 1
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'process {{$labels.process_name}} on host {{$labels.instance}}  is not running  for over 5m.'
      summary: 'elasticsearch process is not running' 
  - alert: alertmanager process is not running
    expr: absent(procstat_pid{job="alertmanager",process_name = "alertmanager"})  == 1
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'process {{$labels.process_name}} on host {{$labels.instance}}  is not running  for over 5m.'
      summary: 'alertmanager process is not running'
  - alert: postfix process is not running
    expr: absent(procstat_pid{job="postfix",pattern = "postfix"})  == 1
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'process {{$labels.pattern}} on host {{$labels.instance}}  is not running  for over 5m.'
      summary: 'postfix process is not running'      
  - alert: blackbox_exporter process is not running
    expr: absent(procstat_pid{job="blackbox_exporter",pattern = "blackbox_exporter"})  == 1
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'process {{$labels.process_name}} on host {{$labels.instance}}  is not running  for over 5m.'
      summary: 'postfix process is not running'            