
groups:
- name: Basic
  rules:
  - alert: Instance is Down
    expr: up == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      description: '{{$labels.instance}} of job {{$labels.job}} has been down for  more than 5 minutes.'
      summary: 'Instance down.'
  - alert: Netowrk interface is down
    expr: ifAdminStatus offset 1m  == 1  and ifAdminStatus != 1 
    for: 2m
    labels:
      severity: critical
    annotations:
      description: 'Network interface {{$labels.ifDescr}} {{$labels.ifName}}  on instance {{$labels.instance}} of job {{$labels.job}} has been down for  more than 1 minutes.'
      summary: 'Network Interface is down.'
  - alert: Network connection is broken
    expr:  ifOperStatus offset 1m  == 1 and ifOperStatus != 1
    for: 2m
    labels:
      severity: critical
    annotations:
      description: 'Connection on network interface {{$labels.ifDescr}} {{$labels.ifName}}  on instance {{$labels.instance}} of job {{$labels.job}} has been broken for 1 minutes '
      summary: 'Network connection is broken'
- name: Cisco switches
  rules:
  - alert: Switch Fan is not working properly
    expr: ciscoEnvMonFanState == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'Switch Fan {{$labels.ciscoEnvMonFanStatusDescr}} of instance {{$labels.instance}} of job {{$labels.job}} is not working properly'
      summary: 'Switch Fan is not working properly.'
  - alert: Swich Power Supply is down
    expr: ciscoEnvMonSupplyState{ciscoEnvMonSupplyStatusDescr=~".*Normal"} == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'Switch Power supply {{$labels.ciscoEnvMonSupplyStatusDescr}} of instance {{$labels.instance}} of job {{$labels.job}} is down'
      summary:  'Switch Power supply  is down.'
  - alert: Switch Temperature is abnormal
    expr: ciscoEnvMonTemperatureState == 0
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'Switch Temperature on module  {{$labels.ciscoEnvMonTemperatureStatusDescr}} of instance {{$labels.instance}} of job {{$labels.job}} is abnormal'
      summary:  'Switch Temperature is abnormal'
  - alert: Switch Temperature value is High
    expr: ciscoEnvMonTemperatureStatusValue >= ciscoEnvMonTemperatureThreshold * 0.8
    for: 5m
    labels:
      severity: warning
    annotations:
      description: 'Switch Temperature value on module  {{$labels.ciscoEnvMonTemperatureStatusDescr}} of instance {{$labels.instance}} of job {{$labels.job}} is high, current value is {{$value}}'
      summary:  'Switch Temperature value is high'
  - alert: Switch Temperaturev value is High
    expr: ciscoEnvMonTemperatureStatusValue >= ciscoEnvMonTemperatureThreshold * 0.9
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'Switch Temperature value on module  {{$labels.ciscoEnvMonTemperatureStatusDescr}} of instance {{$labels.instance}} of job {{$labels.job}} is high, current value is {{$value}}'
      summary:  'Switch Temperature value is high'
  - alert: Switch Memory usage is high
    expr: cpmCPUMemoryUsed{job="switch"} /(cpmCPUMemoryFree{job="switch"} + cpmCPUMemoryUsed{job="switch"}) >= 80
    for: 5m
    labels:
      severity: warning
    annotations:
      description: 'Switch Memory usage Of module {{$labels.cpmCPUTotalIndex}} of instance {{$labels.instance}} of job {{$labels.job}} is high, current value is {{$value}}'
      summary:  'Switch Memory usage is high'
  - alert: Switch Memory usage is high
    expr: cpmCPUMemoryUsed{job="switch"} /(cpmCPUMemoryFree{job="switch"} + cpmCPUMemoryUsed{job="switch"}) >= 90
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'Switch Memory usage Of module {{$labels.cpmCPUTotalIndex}} of instance {{$labels.instance}} of job {{$labels.job}} is high, current value is {{$value}}'
      summary:  'Switch Memory usage is high'
  - alert: Switch CPU usage is high
    expr: cpmCPUTotal5minRev >= 80
    for: 5m
    labels:
      severity: warning
    annotations:
      description: 'Switch CPU usage Of module {{$labels.cpmCPUTotalIndex}} of instance {{$labels.instance}} of job {{$labels.job}} is high, current value is {{$value}}'
      summary:  'Switch CPU usage is high'
  - alert: Switch CPU usage is high
    expr: cpmCPUTotal5minRev >=90
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'Switch CPU usage Of module {{$labels.cpmCPUTotalIndex}} of instance {{$labels.instance}} of job {{$labels.job}} is high, current value is {{$value}}'
      summary:  'Switch CPU usage is high'
- name: Blade servers
  rules:
  - alert: Blade Server Fan is not healthy
    expr: ipmi_fan_speed_state !=0
    for: 5m
    labels:
      severity: warning
    annotations:
      description: 'Blade Servers Fan  of module "{{$labels.name}}" on  {{$labels.hostname}} of job {{$labels.job}} is unhealthy.'
      summary: 'Blade Server Fan is unhealthy.'
  - alert: Blade Server Power State is not healthy
    expr: ipmi_power_state !=0
    for: 5m
    labels:
      severity: warning
    annotations:
      description: 'Blade Servers Power State of module  "{{$labels.name}}" on  {{$labels.hostname}} of job {{$labels.job}} is unhealthy.'
      summary: 'Blade Server Power State is unhealthy.'
  - alert: Blade Server Temperature is not healthy
    expr: ipmi_temperature_state !=0
    for: 5m
    labels:
      severity: warning
    annotations:
      description: 'Blade Servers Temperature  of module  "{{$labels.name}}" on  {{$labels.hostname}} of job {{$labels.job}} is unhealthy.'
      summary: 'Blade Server Temperature is unhealthy.'
  - alert: Blade Server CPU is not healthy
    expr: ipmi_sensor_state{id !="11",type="Processor"} !=0
    for: 5m
    labels:
      severity: warning
    annotations:
      description: 'Blade Servers CPU  "{{$labels.name}}" on  {{$labels.hostname}} of job {{$labels.job}} is unhealthy.'
      summary: 'Blade Server CPU is unhealthy.'
  - alert: Blade Server Memory is not healthy
    expr: ipmi_sensor_state{id !="35",type="Memory"} !=0
    for: 5m
    labels:
      severity: warning
    annotations:
      description: 'Blade Servers Memory  "{{$labels.name}}" on  {{$labels.hostname}} of job {{$labels.job}} is unhealthy.'
      summary: 'Blade Server Memory is unhealthy.'
  - alert: Blade Server Disk is not healthy
    expr: ipmi_sensor_state{name=~"Drive.{2}",type="Drive Slot"} !=0
    for: 5m
    labels:
      severity: warning
    annotations:
      description: 'Blade Servers Disk  "{{$labels.name}}" on  {{$labels.hostname}} of job {{$labels.job}} is unhealthy.'
      summary: 'Blade Server Disk is unhealthy.'
  - alert: Blade Server Power Supply is not healthy
    expr: ipmi_sensor_state{type="Power Supply"} !=0
    for: 5m
    labels:
      severity: warning
    annotations:
      description: 'Blade Servers Power Supply  "{{$labels.name}}" on  {{$labels.hostname}} of job {{$labels.job}} is unhealthy.'
      summary: 'Blade Server Power Supply is unhealthy.'
- name: f5
  rules:
  - alert: F5 Disk usage is high
    expr: dskPercent >= 90
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'Disk  {{$labels.dskDevice}} of instance {{$labels.instance}} of job {{$labels.job}} usage is high, current value is {{$value}}'
      summary: 'F5 Disk usage is high'
  - alert: F5 CPU is not running
    expr: hrDeviceStatus != 2
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'F5 CPU on instance {{$labels.instance}} of job {{$labels.job}} is not running'
      summary: 'F5 CPU is not running'
  - alert: F5 memory usage high
    expr: 1 - (memTotalFree+memBuffer+memShared+memCached) / memTotalReal > 0.9
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'F5 memory usage on instance {{$labels.instance}} of job {{$labels.job}} is high, current value is {{$value}}'
      summary: 'F5 memory usage high'
- name: firewall
  rules:
  - alert: Firewall CPU load15 is high
    expr: cpmCPULoadAvg15mini{job="firewall"} > 12
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'Firewall CPU  load on instance  {{$labels.instance}} of job {{$labels.job}} is high, current value is {{$value}}'
      summary: 'Firewall CPU load15 is high'
      #  - alert: Firewall memory usage  is high
      #    expr: cpmCPUMemoryUsed{job="firewall"} / ( cpmCPUMemoryUsed{job="firewall"} + cpmCPUMemoryFree{job="firewall"} ) > 0.95
      #    for: 5m
      #    labels:
      #      severity: critical
      #    annotations:
      #      description: 'Firewall Memory  usage on instance  {{$labels.instance}} of job {{$labels.job}} is high, current value is {{$value}}'
      #      summary: 'Firewall memory usage is high'
- name: Tape Libary
  rules:
  - alert: Tape Libary is not running normal
    expr: bDTGlobalStatus != 3
    for: 5m
    labels:
      severity: critical
    annotations:
      description: 'Tape Libary of instance  {{$labels.instance}} of job {{$labels.job}} is not running normal'
      summary:  'Tape Libary is not running normal'
- name: netapp
  rules:
  - alert: Netapp Storage has failed disks
    expr: diskFailedCount{job="netapp"} != 0
    for: 3m
    labels:
      severity: critical
    annotations:
      description: 'Netapp storage has {{$labels.diskFailedCount}} failed disks on instance {{$labels.instance}} of job {{$labels.job}},details is {{$labels.diskFailedMessage}}'
      summary:  'Netapp Storage has failed disks'
  - alert: Netapp Storage has prefailed disks
    expr: diskPrefailedCount{job="netapp"} != 0
    for: 3m
    labels:
      severity: critical
    annotations:
      description: 'Netapp storage has {{$labels.diskPrefailedCount}} prefailed disks on instance {{$labels.instance}} of job {{$labels.job}}'
      summary:  'Netapp Storage has prefailed disks'
  - alert: Netapp Storage enclosure communitcation is not active
    expr: enclContactState{job="netapp"} != 3
    for: 3m
    labels:
      severity: critical
    annotations:
      description: 'Netapp storage enclosure {{$labels.enclIndex}} communitcation  on instance {{$labels.instance}} of job {{$labels.job}} is not acitve'
      summary:  'Netapp Storage enclosure communitcation is not active'
  - alert: Netapp Storage enclosure has failed electronics elements
    expr: enclElectronicsFailed{enclElectronicsFailed != "",job="netapp"} == 1
    for: 3m
    labels:
      severity: critical
    annotations:
      description: 'Netapp storage enclosure {{$labels.enclIndex}} has failed electronics elements  on instance {{$labels.instance}} of job {{$labels.job}}'
      summary:  'Netapp Storage enclosure has failed electronics elements'
  - alert: Netapp Storage enclosure has failed  fans
    expr: enclFansFailed{enclFansFailed != "",job="netapp"} == 1
    for: 3m
    labels:
      severity: critical
    annotations:
      description: 'Netapp storage enclosure {{$labels.enclIndex}} has failed fans on instance {{$labels.instance}} of job {{$labels.job}}'
      summary:  'Netapp Storage enclosure has failed  fans'
  - alert: Netapp Storage enclosure has failed  power supplies
    expr: enclPowerSuppliesFailed{enclPowerSuppliesFailed != "",job="netapp"} == 1
    for: 3m
    labels:
      severity: critical
    annotations:
      description: 'Netapp storage enclosure {{$labels.enclIndex}} has failed power supplies on instance {{$labels.instance}} of job {{$labels.job}}'
      summary:  'Netapp Storage enclosure has failed  supplies'
  - alert: Netapp Storage enclosure has  overtemperature failure
    expr: enclTempSensorsOverTempFail{enclTempSensorsOverTempFail != "",job="netapp"} == 1
    for: 3m
    labels:
      severity: critical
    annotations:
      description: 'Netapp storage enclosure {{$labels.enclIndex}} has overtemperature failure on instance {{$labels.instance}} of job {{$labels.job}}'
      summary:  'Netapp Storage enclosure has overtemperature failure'
  - alert: Netapp Storage enclosure has  overtemperature warning
    expr: enclTempSensorsOverTempFail{enclTempSensorsOverTempFail != "",job="netapp"} == 1
    for: 3m
    labels:
      severity: warning
    annotations:
      description: 'Netapp storage enclosure {{$labels.enclIndex}} has overtemperature warning on instance {{$labels.instance}} of job {{$labels.job}}'
      summary:  'Netapp Storage enclosure has overtemperature warning'
  - alert: Netapp Storage enclosure has  overvoltage failure
    expr: enclVoltSensorsOverVoltFail{enclVoltSensorsOverVoltFail != "",job="netapp"} == 1
    for: 3m
    labels:
      severity: critical
    annotations:
      description: 'Netapp storage enclosure {{$labels.enclIndex}} has overvoltage failure on instance {{$labels.instance}} of job {{$labels.job}}'
      summary:  'Netapp Storage enclosure has overvoltae failure'
  - alert: Netapp Storage enclosure has overvoltage warning
    expr: enclVoltSensorsOverVoltWarn{enclVoltSensorsOverVoltWarn != "",job="netapp"} == 1
    for: 3m
    labels:
      severity: warning
    annotations:
      description: 'Netapp storage enclosure {{$labels.enclIndex}} has overvoltage warning on instance {{$labels.instance}} of job {{$labels.job}}'
      summary:  'Netapp Storage enclosure has overvoltage warning'
  - alert: Netapp Storage  plex is offiline
    expr: plexStatus{job="netapp"} == 1
    for: 3m
    labels:
      severity: critical
    annotations:
      description: 'Netapp storage plex {{$labels.plexIndex}} on instance {{$labels.instance}} of job {{$labels.job}} is offline'
      summary:  'Netapp Storage plex is offiline'
  - alert: Netapp Storage volume usage is high
    expr: netapp_capacity_svm_vol_afs_used_percent  > 90
    for: 3m
    labels:
      severity: critical
    annotations:
      description: 'Netapp Storage volume {{$labels.vol }}  in cluster {{$labels.cluster}}  group {{$labels.group}}  svm  {{$labels.svm}}  usage is high, current usage is {{$value}}%'
      summary:  'Netapp Storage volume usage is high'
  - alert: Netapp Storage SVM usage is high
    expr: netapp_capacity_svm_vol_summary_afs_used_percent  > 90
    for: 3m
    labels:
      severity: critical
    annotations:
      description: 'Netapp Storage SVM {{$labels.svm}}   in cluster {{$labels.cluster}}  group {{$labels.group}} usage is high, current usage is {{$value}}%'
      summary:  'Netapp Storage SVM usage is high'
  - alert: Netapp Storage node CPU usage is high
    expr: netapp_perf_node_processor_avg_processor_busy  > 80
    for: 3m
    labels:
      severity: critical
    annotations:
      description: 'Netapp Storage  node {{$labels.node}}   CPU in cluster {{$labels.cluster}}  group {{$labels.group}} usage is high, current usage is {{$value}}%'
      summary:  'Netapp Storage node CPU usage is high'

- name: F5 Objects
  rules:
  - alert: bigip Virtual server is not available
    expr: bigip_vs_status_availability_state{vs !~ "listener_.*"} == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      description: 'OOB monitor: BigIP F5 Virtual server {{$labels.vs}} on instance  {{$labels.instance}} of job {{$labels.job}} has been down for  more than 2 minutes.'
      summary: 'OOB monitor: bigip Virtual server is not available.'
  - alert: bigip pool is not available
    expr: bigip_pool_status_availability_state == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      description: 'OOB monitor: BigIP F5 pool {{$labels.pool}} on instance  {{$labels.instance}} of job {{$labels.job}} has been down for  more than 2 minutes.'
      summary: 'OOB monitor: bigip pool is not available '
- name: URL
  rules:
  - alert: URL is not accessible
    expr: probe_success == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      description: 'OOB monitor: URL  {{$labels.instance}}  is inaccessible'
      summary: 'OOB monitor: URL is not accessible'
