- name: restart_docker_engine
  systemd: 
    name: docker.service
    daemon_reload: yes
    state: restarted
    enabled: yes
    
- name: restart_container_slice
  systemd: 
    name: container.slice
    daemon_reload: yes
    state: restarted
    enabled: yes