---


- name: install auditbeat
  package:
    name: "{{ auditbeat_rpm_url }}"
    state: present
    allow_downgrade: yes  


- name: ensure auditd is installed 
  package:
    name: audit
    state: present

    
- name: create conf for auditbeat 
  template: 
    src: auditbeat.yml.j2 
    dest: /etc/auditbeat/auditbeat.yml 
    owner: root 
    group: root 
    mode: 0755
  notify:
    restart_auditbeat  

- name: start auditbeat
  systemd: 
    name: auditbeat 
    state: restarted 
    enabled: yes 
    daemon_reload: yes