---
- name: check if filebeat is installed 
  shell: filebeat version |grep filebeat|grep {{filebeat_version}}
  register: filebeat
  ignore_errors: yes


- name: install filebeat
  package:
    name: "{{ filebeat_rpm_url }}"
    state: present
    disable_gpg_check: yes  
  register: install
  when: filebeat.rc != 0


- name: create conf for filebeat 
  template: src=filebeat-hana.yml.j2 dest=/etc/filebeat/filebeat.yml owner=root group=root mode=0755
  notify:
    restart_filebeat  

- name: install filebeat.service
  copy: 
    src: filebeat.service
    dest: /lib/systemd/system/filebeat.service

- name: restart filebeat
  systemd: 
    name: filebeat 
    state: restarted 
    enabled: yes 
    daemon_reload: yes

