---
# RHEL/CentOS only. Set a repository to use for PostgreSQL installation.



postgresql_python_library: python-psycopg2
postgresql_postgres_user: postgres
postgresql_postgres_group: postgres

postgresql_unix_socket_directories:
  - /var/run/postgresql
postgresql_listen_addresses: "*"
# Global configuration options that will be set in postgresql.conf.
postgresql_global_config_options:
  - option: unix_socket_directories
    value: '{{ postgresql_unix_socket_directories | join(",") }}'
  - option: listen_addresses
    value: "{{ postgresql_listen_addresses }}"
# Host based authentication (hba) entries to be added to the pg_hba.conf. This
# variable's defaults reflect the defaults that come with a fresh installation.
postgresql_hba_entries:
  - { type: local, database: all, user: postgres, auth_method: trust }
  - { type: local, database: all, user: all, auth_method: peer }
  - { type: host, database: all, user: all, address: all, auth_method: md5 }

# Debian only. Used to generate the locales used by PostgreSQL databases.
postgresql_locales:
  - 'en_US.UTF-8'

