---
# tasks file for powerdns

- name: Include distribution specific variables
  include_vars: "{{ ansible_distribution }}.yml"
  tags:
    - powerdns

- import_tasks: CentOS.yml
  when: ansible_distribution == "CentOS"
  tags:
    - powerdns

- name: Create PowerDNS authoritative server configuration file
  become: yes
  template:
    src: pdns.conf.j2
    dest: "{{ powerdns_authoritative_config_dir }}/pdns.conf"
    owner: root
    group: root
    mode: 0600
  notify:
    - restart powerdns authoritative
  when: powerdns_authoritative
  tags:
    - powerdns
    - authoritative




- name: Create PowerDNS recursor configuration file
  become: yes
  template:
    src: recursor.conf.j2
    dest: "{{ powerdns_recursor_config_dir }}/recursor.conf"
    owner: root
    group: root
    mode: 0644
  notify:
    - restart powerdns recursor
  when: powerdns_recursor
  tags:
    - powerdns
    - recursor

- name: Ensure PowerDNS authoritative service is started and enabled on boot
  service:
    name: "{{ powerdns_authoritative_service_name }}"
    state: restarted
    enabled: yes
  when: powerdns_authoritative
  tags:
    - powerdns
    - authoritative

- name: Ensure PowerDNS recursor service is started and enabled on boot
  service:
    name: "{{ powerdns_recursor_service_name }}"
    state: restarted
    enabled: yes
  when: powerdns_recursor
  tags:
    - powerdns
    - recursor
