- name: add prometheus repo
  yum_repository:
    name: prometheus
    description: prometheus repo
    baseurl: https://packagecloud.io/prometheus-rpm/release/el/7/$basearch
    repo_gpgcheck: 1
    enabled: 1
    gpgkey: https://packagecloud.io/prometheus-rpm/release/gpgkey
            https://raw.githubusercontent.com/lest/prometheus-rpm/master/RPM-GPG-KEY-prometheus-rpm
    gpgcheck: 1
    sslverify: 1
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    metadata_expire: 300

- name: install blackbox_exporter package
  package:
    name: "{{item}}"
    state: latest
  with_items:
  - blackbox_exporter

- name: create blackbox_exporter conf dir
  file:
    path: /etc/prometheus/
    state: directory
    mode: 0755


- name: create blackbox_exporter service file
  copy:
    src: blackbox_exporter.service
    dest: /lib/systemd/system/blackbox_exporter.service
  register: blackbox_exporter_service

- name: create blackbox_exporter conf file 
  template:
    src: blackbox_exporter.yml.j2
    dest: /etc/prometheus/blackbox_exporter.yml
  register: blackbox_exporter_conf
- name: create ca  cert  file 
  copy:
    src: ca.pem
    dest: "{{blackbox_exporter_ca_path}}"

- name: restart blackbox_exporter 
  systemd: 
    name: blackbox_exporter 
    state: restarted 
    enabled: yes
    daemon_reload: yes
  when: blackbox_exporter_conf is changed or blackbox_exporter_service is changed

- name: add firewalld rules
  firewalld:
    zone: public
    port: 9115/tcp
    permanent: true
    state: enabled
- name: reload firewalld
  shell: firewall-cmd --reload    
    