- name: Define fluent-bit conf source.
  set_fact:
    td_agent_bit_conf_src: haha-td-agent-bit.conf.j2
  when: td_agent_bit_on_hana

- name: Define fluent-bit conf source.
  set_fact:
    td_agent_bit_conf_src: td-agent-bit.conf.j2
  when: td_agent_bit_on_hana is not defined

- name: Define fluent-bit parser source.
  set_fact:
    td_agent_bit_parser_src: hana-parsers.conf
  when: td_agent_bit_on_hana

- name: Define fluent-bit parser source.
  set_fact:
    td_agent_bit_parser_src: parsers.conf
  when: td_agent_bit_on_hana is not defined