
powerdns_authoritative_dnsupdate: yes
powerdns_authoritative_allow_dnsupdate_from:
  - 127.0.0.0/8
  - ::1
  - 192.168.0.0/16
powerdns_authoritative_api: yes
powerdns_authoritative_api_key: jennings
powerdns_authoritative_api_logfile: /var/log/pdns.log
powerdns_authoritative_local_address:
  - 127.0.0.1
powerdns_authoritative_local_port: 5300 
powerdns_authoritative_webserver: yes
powerdns_authoritative_webserver_address: 0.0.0.0
powerdns_authoritative_webserver_port: 8081
powerdns_authoritative_webserver_password: jennings
powerdns_authoritative_webserver_allow_from:
  - 192.168.0.0/16
  - 127.0.0.1
powerdns_authoritative_launch: gpgsql
powerdns_backend_generic_postgresql_host: 192.168.59.139
powerdns_backend_generic_postgresql_port: 5432
powerdns_backend_generic_postgresql_dbname: pdns
powerdns_backend_generic_postgresql_user: pdns 
powerdns_backend_generic_postgresql_password: pdns 
powerdns_backend_generic_postgresql_dnssec: no




powerdns_recursor_local_address:
  - 0.0.0.0
powerdns_recursor_local_port: 53
powerdns_recursor_allow_from: 
  - 127.0.0.1
  - 192.168.0.0/16
powerdns_recursor_api_key: jennings
powerdns_recursor_webserver: yes
powerdns_recursor_webserver_address: 
    - 0.0.0.0
powerdns_recursor_webserver_port: 8082
powerdns_recursor_webserver_allow_from:
  - 192.168.0.0/16
  - 127.0.0.1
powerdns_recursor_webserver_password: jennings

powerdns_recursor_forward_zones: 
  - snfc.org=127.0.0.1:5300
  - .=223.5.5.5:53
  - 168.192.in-addr.arpa=127.0.0.1:5300




