---
# defaults file for rsync-server

rsync_server_timeout: 300
rsync_server_max_connections: 10
rsync_server_pass: pass
rsync_server_secrets_file: /etc/rsync.pass
rsync_server_shares: 
- name: dataset-1
  path: /data
  ignore_error: true
  list: false
  readonly: false
  secrets_file: {{ rsync_server_secrets_file }}
  hosts_allow: 
  - 192.168.59.130
  munge_symlinks: false

rsync_server_logrotate_interval: weekly
rsync_server_logrotate_backlog_size: 52
