---
- name: Configure global settings.
  lineinfile:
    dest: "{{ postgresql_config_path }}/postgresql.conf"
    regexp: "^#?{{ item.option }}.+$"
    line: "{{ item.option }} = '{{ item.value }}'"
    state: "{{ item.state | default('present') }}"
  with_items: "{{ postgresql_global_config_options }}"
  notify: restart postgresql

- name: Configure host based authentication (if entries are configured).
  template:
    src: "templates/pg_hba.conf.j2"
    dest: "{{ postgresql_config_path }}/pg_hba.conf"
    owner: "{{ postgresql_postgres_user }}"
    group: "{{ postgresql_postgres_group }}"
    mode: 0600
  notify: restart postgresql
  when: postgresql_hba_entries

- name: Ensure PostgreSQL unix socket dirs exist.
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ postgresql_postgres_user }}"
    group: "{{ postgresql_postgres_group }}"
    mode: 02775
  with_items: "{{ postgresql_unix_socket_directories }}"

- name: change PGDATA environment in service file
  lineinfile:
    dest: "/lib/systemd/system/{{ postgresql_daemon }}.service"
    regexp: "^Environment=PGDATA=.*$"
    line: "Environment=PGDATA={{ postgresql_data_dir }}"
    state: present
  notify: restart postgresql
  