---
# Variable configuration.
- import_tasks: variables.yml
  static: no

# Setup/install tasks.
- import_tasks: setup-CentOS.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'CentOS'
  static: no

- import_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat' and ansible_distribution == 'RedHat'
  static: no

- import_tasks: initialize.yml
- import_tasks: configure.yml

- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: "{{ postgresql_daemon }}"
    state: restarted
    enabled: yes
    
- import_tasks: users.yml
