---
- name: set super user postgres  password.
  postgresql_user:
    name: postgres
    password: "{{  pgsql_postgres_password }}"
    encrypted: yes
  no_log: false
  become: yes
  become_user: postgres
  become_method: enable
  environment:
#    PGPASSWORD: "{{  pgsql_postgres_password }}"
  vars:
    ansible_ssh_pipelining: true
