
- name: run the playbook tasks on the localhost
  hosts: 127.0.0.1
  connection: local
  become: yes
  roles:
  - ansible-role-logstash
  vars:
  - LOGSTAASH_VERSION: 6.4.3
  - ES_CLUSTER_INSTANCE_1: 10.36.52.184
  - ES_CLUSTER_INSTANCE_2: 10.36.52.185
  - ES_CLUSTER_INSTANCE_3: 10.36.52.186
  - KIBANA_INSTANCE: 10.36.52.175
  - KIBANA_USER: user
  - KIBANA_PASS: pass
