- name: uninstall ntpd if installed
  package:
    name: ntp
    state: absent
  when: ansible_os_family == "RedHat"     

- name: install chrony
  package:
    name: chrony
    state: present
  when: ansible_os_family == "RedHat"     

- name: install chrony conf
  template:
    src: chrony.conf.j2
    dest: /etc/chrony.conf
  when: ansible_os_family == "RedHat"     
  register: chrony_conf
- name: start chrony
  systemd:
    name: chronyd
    state: restarted
    enabled: yes
    daemon_reload: yes
  when: ansible_os_family == "RedHat"      and chrony_conf is changed
