LOGSTASH_DATA_PATH: /var/lib/logstash
LOGSTASH_LOGS_PATH: /var/log/logstash
LOGSTASH_JVM_XMX_SIZE: 4G
LOGSTASH_JVM_XMS_SIZE: 4G
ES_CLUSTER_INSTANCE_1: 
ES_CLUSTER_INSTANCE_2:
ES_CLUSTER_INSTANCE_3:
ES_CLUSTER_USER:
ES_CLUSTER_PASS:
KIBABA_SCHEMA: http
KIBANA_INSTANCE: loclahost:5601
KIBANA_USER:
KIBANA_PASS:
LOGSTASH_ENABLED_PIPELINES:
- {'id': 'elastiflow','path': '/etc/logstash/elastiflow/conf.d/*.conf'}
- {'id': 'cef','path': '/etc/logstash/cef/conf.d/*.conf'}
