- name: Apply config for lsyncd
  template: src=lsyncd.j2 dest=/etc/lsyncd.conf owner=root group=root mode=0755
  notify:
    restart_lsyncd

- name: Apply exclude file for lsyncd
  lineinfile:
    path: "{{ lsyncd_exclude_file }}"
    line:  "{{ item }}"
    create: yes
    state: present
  with_items: "{{lsyncd_exclude_file_lines}}"
  notify:
    restart_lsyncd

- name: create pass file
  lineinfile:
    path: "{{ lsyncd_passwd_file }}"
    line: "{{ lsyncd_passwd }}"
    create: yes
    state: present
  notify:
      restart_lsyncd