- name: create journald log dir
  file:
    path: /var/log/journal
    state: directory
    mode: 0755

- name: restart journald
  systemd: 
    name: systemd-journald.service 
    state: restarted 
    enabled: yes
    daemon_reload: yes

- name: configure journald
  copy: 
    src: journald.conf 
    dest: /etc/systemd/journald.conf 
    mode: 0755 
    owner: root
  notify:
    restart_journald