---
# tasks file for rsync-server

- name: rsyncd | install rsync
  yum:
    name: rsync
    state: present

- name: rsyncd | create log directory
  file:
    path: /var/log/rsyncd
    state: directory

- name: rsyncd | configure shares
  template:
    dest: /etc/rsyncd.conf
    src: etc-rsyncd-conf.j2
  # No need to reload, file is re-read on each client connection.
- name: create pass file
  lineinfile:
    path: "{{ rsync_server_secrets_file }}"
    line: "{{ rsync_server_pass }}"
    create: yes
    state: present
  notify:
      restart_lsyncd
  
- name: rsyncd | configure logrotate
  template:
    backup: no
    dest: /etc/logrotate.d/rsyncd
    src: logrotated-rsyncd.j2

- name: rsyncd | start and enable service
  systemd:
    name: rsyncd
    enabled: yes
    state: restarted
    daemon_reload: yes
