---
- name: Clone a VM from Template and customize
  vmware_guest:
    hostname: 192.168.1.209
    username: administrator@vsphere.local
    password: vmware
    validate_certs: no
    datacenter: datacenter1
    cluster: cluster
    resource_pool: resource_pool
    folder: datacenter1/nginx
    name: nginx
    template: template-centos
    networks:
    - name: VM Network
      type: static
      ip: 192.168.1.100
      netmask: 255.255.255.0
      gateway: 192.168.1.1
      domain: my_domain
      dns_servers:
      - 192.168.1.1
      - 192.168.1.2
    - name: VM Network2
      type: dhcp
    state: poweredon
    wait_for_ip_address: yes
    customization:
      dns_servers:
      - 192.168.1.1
      - 192.168.1.2
      runonce:
      - echo "abbc"
  delegate_to: localhost
  register: vm-instance