

- name: add prometheus repo
  yum_repository:
    name: prometheus
    description: prometheus repo
    baseurl: https://packagecloud.io/prometheus-rpm/release/el/7/$basearch
    repo_gpgcheck: 1
    enabled: 1
    gpgkey: https://packagecloud.io/prometheus-rpm/release/gpgkey
            https://raw.githubusercontent.com/lest/prometheus-rpm/master/RPM-GPG-KEY-prometheus-rpm
    gpgcheck: 1
    sslverify: 1
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    metadata_expire: 300
- name: install prometheus package
  package:
    name: "{{item}}"
    state: latest
  with_items:
  - prometheus2

- name: create prometheus service file
  template:
    src: prometheus.service.j2
    dest: /lib/systemd/system/prometheus.service
  register: prometheus_service
  notify: restart_prometheus


- name: create prometheus file sd dir
  file:
    path: /etc/prometheus/tgroups/
    state: directory
    mode: 0755
    owner: prometheus
    group: prometheus


- name: create prometheus conf file
  template:
    src: "{{item.src}}"
    dest: "{{item.target}}"
    mode: 0755
    owner: prometheus
    group: prometheus
  with_items:
  - {src: "alertmanagers.yml.j2",target: "/etc/prometheus/alertmanagers.yml"}
  - {src: "prometheus.yml.j2",target: "/etc/prometheus/prometheus.yml"}
  register: prometheus_conf


- name: create alert.rules.yml conf file
  copy:
    src: "{{item}}"
    dest: /etc/prometheus/
  with_fileglob:
    - "{{ role_path }}/files/*.alert.rules.yml"
  register: prometheus_alerts_rules

- name: check prometheus service state 
  service_facts:
- name: start prometheus service if not running
  systemd: 
    name: prometheus
    state: started
    enabled: yes
    daemon_reload: yes
  when: ansible_facts.services['prometheus'].state  == "stopped"

- name: reload prometheus if needed 
  uri:
    url: http://localhost:9090/-/reload
    method: POST
  when: (prometheus_conf is changed or prometheus_alerts_rules is changed  ) and ansible_facts.services['prometheus'].state  == "running"


- name: change file owner
  file:
    path: "{{item}}"
    owner: prometheus
    group: prometheus
    recurse: yes
  with_items:
  - "{{ prometheus_storage_tsdb_path}}"
  - /etc/prometheus



- name: and more targets
  copy:
    src: "{{item}}"
    dest: /etc/prometheus/tgroups/
    mode: 0755
  with_fileglob:
    - "{{ role_path }}/files/*-targets.yml"




