- name: set selinux enfore to false if it is running 
  selinux:
    state: disabled
- name: disable selinux
  lineinfile:
    path: /etc/sysconfig/selinux
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'
  when: ansible_os_family == "RedHat"


- name: disable selinux
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=disabled'
  when: ansible_os_family == "Suse"

- name: disable selinux
  lineinfile:
    path: /etc/selinux/config
    regexp: '^enforcing='
    line: 'enforcing=0'
  when: ansible_os_family == "Suse"


