---
#- name: install new docker repo
#  copy: src=docker-el{{ ansible_distribution_major_version }}.repo dest=/etc/yum.repos.d/docker-el{{ ansible_distribution_major_version }}.repo
#- name: install docker-engin
#  yum: name=docker-engine state=latest
#- name: create docker group and add weblogic to this group
#  group: name=docker state=present
- name: update docker service file
  copy: src=docker.service  dest=/usr/lib/systemd/system/docker.service 
  notify: daemon-reload
#- name: add weblogic to docker
#  user: name=weblogic uid=102  password=$6$gYCH.Nbcem9bhCn$HlrZg.3Hx.G0ENzx43m7TRqb87.P1rkXFqtmSEK2GPU3nRTbL29QPCWNlm1TPhGiIMzDCZJK6KcBuenuIY0OK/ groups=docker append=yes
- name: restart docker service
  service: name=docker state=restarted enabled=yes
#- name: install Docker Compose
#  shell: curl -L https://github.com/docker/compose/releases/download/1.8.0/docker-compose-$(uname -s)-$(uname -m) > /usr/bin/docker-compose ; chmod +x /usr/bin/docker-compose
#- name: install Docker Compose Command-line Completion
#  shell:  curl -L https://raw.githubusercontent.com/docker/compose/$(docker-compose version --short)/contrib/completion/bash/docker-compose > /etc/bash_completion.d/docker-compose
