---
postgresql_python_library: python-psycopg2
postgresql_postgres_user: postgres
postgresql_postgres_group: postgres
postgresql_unix_socket_directories:
  - /var/run/postgresql
# Databases to ensure exist.
postgresql_databases:
  - name: "{{ pgsql_db_name }}"
    owner: "{{ pgsql_db_owner }}"

  #   lc_collate: # defaults to 'en_US.UTF_8'
  #   lc_ctype: # defaults to 'en_US.UTF_8'
  #   encoding: # defaults to 'UTF_8'
  #   template: # defaults to 'template0'
  #   login_host: # defaults to 'localhost'
    login_password: "{{pgsql_postgres_password}}" # defaults to not set
    login_user:  "{{pgsql_postgres_user}}" # defaults to '{{ postgresql_user }}'
  #   login_unix_socket: # defaults to 1st of postgresql_unix_socket_directories
  #   port: # defaults to not set
  #   state: # defaults to 'present'

# Users to ensure exist.pgsql_postgres_password
postgresql_users: 
  - name: "{{ pgsql_user_name }}"
    password:  "{{pgsql_user_password}}"
  #   password: # defaults to not set
  #   priv: # defaults to not set
    role_attr_flags: LOGIN  # defaults to not set
  #   db: # defaults to not set
    login_host:  localhost # defaults to 'localhost'
    login_password: "{{pgsql_postgres_password}}"  # defaults to not set
    login_user: "{{pgsql_postgres_user}}" # defaults to '{{ postgresql_user }}'
    login_unix_socket: # defaults to 1st of postgresql_unix_socket_directories
  #   port: # defaults to not set
  #   state: # defaults to 'present'
