ipmi_exporter_version: 1.0.0
ipmi_exporter_binary_url: https://github.com/jenningsloy318/ipmi_exporter/releases/download/{{ipmi_exporter_version}}/ipmi_exporter-{{ipmi_exporter_version}}.linux-amd64.tar.gz
ipmi_targets:
- {"host": "default", "user": "user","pass": "pass"}
ipmi_exclude_sensor_ids:
- 2
- 29
- 32
- 50
- 52
- 55
- 80
- 81
- 82
- 83
- 84
- 85
- 86
- 87
