blackbox_exporter_version: 0.12.0
blackbox_exporter_binary_url: https://github.com/prometheus/blackbox_exporter/releases/download/v{{blackbox_exporter_version}}/blackbox_exporter-{{blackbox_exporter_version}}.linux-amd64.tar.gz

blackbox_exporter_ca_path: /etc/blackbox_exporter/ca.pem
