- name: check version
  shell: /usr/bin/alertmanager  --version |grep alert|awk '{print $3}'|grep {{ alertmanager_version }}
  register: alertmanager
  ignore_errors: yes

- debug:
    var=alertmanager.stdout_lines
- name: Unarchive a file that needs to be downloaded
  unarchive:
    src: "{{ alertmanager_bin_url }}"
    dest: /tmp
    remote_src: yes
  when:  alertmanager.stdout_lines  != ""


- name: copy alertmanager binary
  copy:
    src: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64/alertmanager"
    dest: /usr/bin
    remote_src: yes
    mode: 0755
  when:  alertmanager.stdout_lines  != ""
- name: copy alertmanager  amtool binary
  copy:
    src: "/tmp/alertmanager-{{ alertmanager_version }}.linux-amd64/amtool"
    dest: /usr/bin
    remote_src: yes
    mode: 0755
  when:  alertmanager.stdout_lines  != ""

- name: create alertmanager service file
  template:
    src: alertmanager.service
    dest: /lib/systemd/system/alertmanager.service

- name: create alertmanager conf dir
  file:
    path: /etc/alertmanager/
    state: directory
    mode: 0755

- name: create alertmanager conf file (part 1)
  template:
    src: alertmanager-1.yml.j2
    dest: /etc/alertmanager/alertmanager-1.yml

- name: create alertmanager conf file (part 2)
  copy:
    src: alertmanager-2.yaml
    dest: /etc/alertmanager/alertmanager-2.yml
- name: create alertmanager conf file
  shell: cat /etc/alertmanager/alertmanager-1.yml /etc/alertmanager/alertmanager-2.yml  >/etc/alertmanager/alertmanager.yml
  notify:
    restart_alertmanager
- name: start alertmanager 
  systemd: 
    name: alertmanager 
    state: restarted 
    enabled: yes
    daemon_reload: yes
- name: add firewalld rules
  firewalld:
    zone: public
    port: 9093-9094/tcp
    permanent: true
    state: enabled
- name: reload firewalld
  shell: firewall-cmd --reload