
- name: add prometheus repo
  yum_repository:
    name: prometheus
    description: prometheus repo
    baseurl: https://packagecloud.io/prometheus-rpm/release/el/7/$basearch
    repo_gpgcheck: 1
    enabled: 1
    gpgkey: https://packagecloud.io/prometheus-rpm/release/gpgkey
            https://raw.githubusercontent.com/lest/prometheus-rpm/master/RPM-GPG-KEY-prometheus-rpm
    gpgcheck: 1
    sslverify: 1
    sslcacert: /etc/pki/tls/certs/ca-bundle.crt
    metadata_expire: 300
- name: install alertmanager package
  package:
    name: "{{item}}"
    state: latest
  with_items:
  - alertmanager

- name: create alertmanager service file
  template:
    src: alertmanager.service
    dest: /usr/lib/systemd/system/alertmanager.service

- name: create alertmanager conf dir
  file:
    path: /etc/prometheus/
    state: directory
    mode: 0755
    owner: prometheus
    group: prometheus


- name: create alertmanager conf file
  template:
    src: alertmanager.yml.j2
    dest: /etc/prometheus/alertmanager.yml
  notify:
    reload_alertmanager_conf



- name: start alertmanager if not running
  systemd: 
    name: alertmanager 
    state: started 
    enabled: yes
    daemon_reload: yes


- name: change file owner
  file:
    path: "{{item}}"
    owner: prometheus
    group: prometheus
    recurse: yes
  with_items:
  - "{{alertmanager_storage_path }}"
  - /etc/alertmanager
  notify:
    reload_alertmanager_conf