---
# Variable configuration.
- name: Ensure PostgreSQL Python libraries are installed.
  package:
    name: "{{ postgresql_python_library }}"
    state: installed
# Configure PostgreSQL.
- import_tasks: users.yml
- import_tasks: databases.yml


