- name: and more targets
  copy:
    src: "{{item}}"
    dest: /etc/prometheus/tgroups/
    mode: 0755
    owner: prometheus
    group: prometheus
  with_items:
  - service-targets.yml
  - telegraf-targets.yml
  - url-targets.yml
