{
 "title": "HANA Process Monitor",
 "time": { "from": "now/d", "to": "now/d" },
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": "label_values(up{job=~\"tegraf-nodes\",app=~\"hana.*\"},instance)"
   },
   {
    "name": "Process",
    "query": "label_values(procstat_pid{job=~\"tegraf-nodes\",instance=~\"$Instance\"}, process_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Process Running Status",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "procstat_pid{instance=\"$Instance\",process_name=\"$Process\",type=\"node\"}"
    }
   ]
  },
  {
   "title": "Threads of The Process",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "procstat_num_threads{instance=\"$Instance\",process_name=\"$Process\",type=\"node\"}"
    }
   ]
  },
  {
   "title": "Open File Descriptor of The Process",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "procstat_num_fds{instance=\"$Instance\",process_name=\"$Process\",type=\"node\"}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "procstat_memory_rss{instance=\"$Instance\",process_name=\"$Process\",type=\"node\"}",
     "legendFormat": "{{instance}}:  {{process_name}} "
    }
   ]
  },
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "procstat_cpu_usage{instance=\"$Instance\",process_name=\"$Process\",type=\"node\"}",
     "legendFormat": "{{instance}}:  {{process_name}} "
    }
   ]
  }
 ]
}