{
 "title": "HANA Monitor",
 "time": { "from": "now/d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Instance",
    "query": "label_values(hana_up, instance)"
   },
   {
    "name": "service_name",
    "query": "label_values(hana_sys_m_service_statistics_process_physical_memory,service_name)"
   }
  ]
 },
 "panels": [
  { "title": "Overall Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HANA Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "hana_up{instance=\"$Instance\",env!=\"\"}"
    }
   ]
  },
  {
   "title": "Replication Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 3, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hana_sys_m_service_replication_replication_status{instance=\"$Instance\",env !=\"\"})"
    }
   ]
  },
  {
   "title": "Licence",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true
  },
  {
   "title": "License Expires",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "hana_sys_m_license_expire_days{ instance =\"$Instance\",env !=\"\"}"
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "$service_name",
     "type": "singlestat",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 7 },
     "repeat": "service_name",
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "hana_sys_m_service_statistics_status{instance=\"$Instance\",service_name=\"$service_name\"}"
      }
     ]
    },
    {
     "title": "$service_name",
     "type": "singlestat",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 7 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "hana_sys_m_service_statistics_status{instance=\"$Instance\",service_name=\"$service_name\"}"
      }
     ]
    },
    {
     "title": "$service_name",
     "type": "singlestat",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 7 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "hana_sys_m_service_statistics_status{instance=\"$Instance\",service_name=\"$service_name\"}"
      }
     ]
    },
    {
     "title": "$service_name",
     "type": "singlestat",
     "gridPos": { "h": 9, "w": 6, "x": 18, "y": 7 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "hana_sys_m_service_statistics_status{instance=\"$Instance\",service_name=\"$service_name\"}"
      }
     ]
    },
    {
     "title": "$service_name",
     "type": "singlestat",
     "gridPos": { "h": 9, "w": 6, "x": 0, "y": 16 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "hana_sys_m_service_statistics_status{instance=\"$Instance\",service_name=\"$service_name\"}"
      }
     ]
    },
    {
     "title": "$service_name",
     "type": "singlestat",
     "gridPos": { "h": 9, "w": 6, "x": 6, "y": 16 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "hana_sys_m_service_statistics_status{instance=\"$Instance\",service_name=\"$service_name\"}"
      }
     ]
    },
    {
     "title": "$service_name",
     "type": "singlestat",
     "gridPos": { "h": 9, "w": 6, "x": 12, "y": 16 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "hana_sys_m_service_statistics_status{instance=\"$Instance\",service_name=\"$service_name\"}"
      }
     ]
    }
   ]
  },
  { "title": "Memory Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "HANA Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hana_sys_m_service_statistics_process_physical_memory{instance=\"$Instance\",service_name !=\"daemon\"}) \r\n /avg(hana_sys_m_service_statistics_physical_memory{instance=\"$Instance\",service_name !=\"daemon\"})"
    }
   ]
  },
  {
   "title": "nameserver",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 18 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hana_sys_m_service_statistics_process_physical_memory{instance=\"10.36.50.13:30015\",service_name=\"nameserver\"}) \r\n /avg(hana_sys_m_service_statistics_physical_memory{instance=\"$Instance\",service_name !=\"daemon\"})"
    }
   ]
  },
  {
   "title": "preprocessor",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 18 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hana_sys_m_service_statistics_process_physical_memory{instance=\"$Instance\",service_name=\"preprocessor\"}) \r\n /avg(hana_sys_m_service_statistics_physical_memory{instance=\"$Instance\",service_name !=\"daemon\"})"
    }
   ]
  },
  {
   "title": "xsengine",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 18 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hana_sys_m_service_statistics_process_physical_memory{instance=\"$Instance\",service_name=\"xsengine\"}) \r\n /avg(hana_sys_m_service_statistics_physical_memory{instance=\"$Instance\",service_name !=\"daemon\"})"
    }
   ]
  },
  {
   "title": "compileserver",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 18 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hana_sys_m_service_statistics_process_physical_memory{instance=\"$Instance\",service_name=\"compileserver\"}) \r\n /avg(hana_sys_m_service_statistics_physical_memory{instance=\"$Instance\",service_name !=\"daemon\"})"
    }
   ]
  },
  {
   "title": "indexserver",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 18 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hana_sys_m_service_statistics_process_physical_memory{instance=\"$Instance\",service_name=\"indexserver\"}) \r\n /avg(hana_sys_m_service_statistics_physical_memory{instance=\"$Instance\",service_name !=\"daemon\"})"
    }
   ]
  },
  {
   "title": "webdispatcher",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 18 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(hana_sys_m_service_statistics_process_physical_memory{instance=\"$Instance\",service_name=\"webdispatcher\"}) \r\n /avg(hana_sys_m_service_statistics_physical_memory{instance=\"$Instance\",service_name !=\"daemon\"})"
    }
   ]
  },
  { "title": "HANA Volume", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "HANA Volume Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "hana_sys_m_disks_used_size{instance=\"$Instance\"}/hana_sys_m_disks_total_size{instance=\"$Instance\"}",
     "legendFormat": "{{instance}}: {{usage_type}}: {{path}}"
    }
   ]
  },
  {
   "title": "Runtime data for column tables.",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }
  },
  {
   "title": "Record Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(hana_sys_m_cs_tables_record_count{instance=\"$Instance\"}[1h]) >1000",
     "legendFormat": "record_count: {{schema_name}}:{{table_name}}"
    }
   ]
  },
  {
   "title": "Write Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(hana_sys_m_cs_tables_write_count{instance=\"$Instance\"}[1h]) >1000",
     "legendFormat": "write_count: {{schema_name}}:{{table_name}}"
    }
   ]
  },
  {
   "title": "Read Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(hana_sys_m_cs_tables_read_count{instance=\"$Instance\"}[1h]) >1000",
     "legendFormat": "read_count: {{schema_name}}:{{table_name}}"
    }
   ]
  },
  {
   "title": "Merge Count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(hana_sys_m_cs_tables_merge_count{instance=\"$Instance\"}[1h]) >1000",
     "legendFormat": "merge_count: {{schema_name}}:{{table_name}}"
    }
   ]
  },
  {
   "title": "Top Memory Usage Tables",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(3,hana_sys_m_cs_tables_memory_size_in_total{instance=\"$Instance\"})",
     "legendFormat": "merge_count: {{schema_name}}:{{table_name}}"
    }
   ]
  }
 ]
}