{
 "title": "Host Monitor2",
 "time": { "from": "now/M", "to": "now" },
 "templating": {
  "list": [
   { "name": "Instance", "label": "Instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "Host Status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=\"$Instance\",type=\"node\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "system_uptime{instance=\"$Instance\",type=\"node\"}"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "processes_total{instance=\"$Instance\",type=\"node\"}"
    }
   ]
  },
  {
   "title": "CPUs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "system_n_cpus{instance=\"$Instance\",type=\"node\"}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "mem_used_percent{instance=\"$Instance\",type=\"node\"}"
    },
    {}
   ]
  },
  {
   "title": "Host Availability",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(up{instance=\"$Instance\",type=\"node\",env !=\"\"}[1w])/count_over_time(up{instance=\"$Instance\",type=\"node\"}[1w])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Host Loads",
   "type": "graph",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "system_load1{instance=\"$Instance\",type=\"node\",env!=\"\"}",
     "legendFormat": "{{instance}}: system_load1"
    },
    {
     "expr": "system_load5{instance=\"$Instance\",type=\"node\",env!=\"\"}",
     "legendFormat": " {{instance}}: system_load5"
    },
    {
     "expr": "system_load15{instance=\"$Instance\",type=\"node\",env!=\"\"}",
     "legendFormat": " {{instance}}: system_load15"
    }
   ]
  },
  {
   "title": "Host CPU usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 -(cpu_usage_idle{instance=~ \"$Instance\",cpu=\"cpu-total\",type=\"node\",env !=\"\"} + cpu_usage_iowait{instance=~ \"$Instance\",cpu=\"cpu-total\",type=\"node\",env !=\"\"}) ",
     "legendFormat": "{{instance}}: CPU usage"
    }
   ]
  },
  {
   "title": "Host Memory Usage(used))",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mem_used_percent{instance=\"$Instance\",type=\"node\"}",
     "legendFormat": "{{instance}}: Memory usage"
    }
   ]
  },
  {
   "title": "Host Disk Usage(Used)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "disk_used_percent{instance=\"$Instance\",fstype!=\"rootfs\",type=\"node\",env!=\"\"}",
     "legendFormat": "{{instance}}: {{path}}"
    }
   ]
  },
  {
   "title": "Network Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nstat_TcpCurrEstab{instance=\"$Instance\",type=\"node\",env !=\"\"}",
     "legendFormat": "{{instance}}: Current Established Connection "
    },
    {
     "expr": "nstat_TcpActiveOpens{instance=\"$Instance\",type=\"node\",env !=\"\"}",
     "legendFormat": "{{instance}}: Active Open Connections "
    },
    {
     "expr": "nstat_TcpAttemptFails{instance=\"$Instance\",type=\"node\",env !=\"\"}",
     "legendFormat": "{{instance}}: Attemp Fails"
    },
    {
     "expr": "nstat_TcpEstabResets{instance=\"$Instance\",type=\"node\",env !=\"\"}",
     "legendFormat": "{{instance}}: Connection resets"
    }
   ]
  }
 ]
}