{
 "title": "Overall Status",
 "time": { "from": "now/d", "to": "now" },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Alerts",
   "type": "singlestat",
   "gridPos": { "h": 10, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "labelSelector": "*", "target": "Query", "type": "single" }
   ]
  },
  {
   "title": "Critical Alerts",
   "type": "table",
   "gridPos": { "h": 5, "w": 18, "x": 5, "y": 1 },
   "targets": [
    {
     "expr": "severity=\"critical\"",
     "labelSelector": " instance,job,summary",
     "target": "Query",
     "type": "table"
    }
   ]
  },
  {
   "title": "Warning Alerts",
   "type": "table",
   "gridPos": { "h": 5, "w": 18, "x": 5, "y": 6 },
   "targets": [
    {
     "expr": "severity=\"warning\"",
     "labelSelector": " instance,job,summary",
     "target": "Query",
     "type": "table"
    }
   ]
  },
  { "title": "Website Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Website Down",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(probe_success{type=\"URL\"} )==0"
    }
   ]
  },
  {
   "title": "Website UP Status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 11, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(probe_success{type=\"URL\"} ==1)"
    }
   ]
  },
  {
   "title": "Overall Website Availability",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(probe_success{type=\"URL\"}[2w])/count_over_time(probe_success{type=\"URL\"}[2w])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Overall Website Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Overall Website UP status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "probe_success{type=\"URL\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Host Monitor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Host Down",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{type=\"node\"}) ==0"
    }
   ]
  },
  {
   "title": "Host UP",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 11, "x": 12, "y": 42 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(up{type=\"node\"} ==1)"
    }
   ]
  },
  {
   "title": "Overall Host Availability",
   "type": "graph",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(up{instance =~ \"10.36.50.*\",type=\"node\"}[2w])/count_over_time(up{instance =~ \"10.36.50.*\",type=\"node\"}[2w])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Overall CPU Uaage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 57 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": " 100 - (cpu_usage_idle{instance=~ \"10.36.50.*\",cpu=\"cpu-total\",type=\"node\"} + cpu_usage_iowait{instance=~ \"10.36.50.*\",cpu=\"cpu-total\",type=\"node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Overall Memory Uaage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "mem_used_percent{instance=~ \"10.36.50.*\",type=\"node\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Overall Disk Uaage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "disk_used_percent{path =~ \"^/$|^/hana$|^/backup$\",instance =~ \"10.36.50.*\",type=\"node\"}",
     "legendFormat": "{{instance}}:{{path}}"
    }
   ]
  }
 ]
}