{
 "title": "WAF Log",
 "time": { "from": "now/M", "to": "now/M" },
 "panels": [
  {
   "title": "Blocks",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "POLICY_NAME.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "5" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "REQUEST_STATUS.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_term", "size": "5" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "REQUEST_STATUS: \"blocked\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Firewall Denied IP",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "CLIENT_IP.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "REQUEST_STATUS: \"blocked\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Request Status Summary",
   "type": "table",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "REQUEST_STATUS.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Violations",
   "type": "table",
   "gridPos": { "h": 6, "w": 8, "x": 7, "y": 6 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "VIOLATIONS.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Top Attacts",
   "type": "table",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 6 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "ATTACK_TYPE.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "5" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "F5 LOG - Grafana",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Grafana",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "metrics": [
        {
         "field": "select field",
         "id": "1",
         "meta": {},
         "settings": { "size": 500 },
         "type": "raw_document"
        }
       ],
       "query": "POLICY_NAME:\"/Common/vs_grafana_3000\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  {
   "title": "F5 LOG - HANA QA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "HANA QA",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "metrics": [
        {
         "field": "select field",
         "id": "1",
         "meta": {},
         "settings": { "size": 500 },
         "type": "raw_document"
        }
       ],
       "query": "POLICY_NAME:\"/Common/vs_hana_qa_8000\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  },
  { "title": "F5 Log - HANA PROD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "HANA Prod",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_document"
      }
     ],
     "query": "POLICY_NAME:\"/Common/vs_hana_prod_8000\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "F5 LOG - HANA Staging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "HANA Staging",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 16 },
     "targets": [
      {
       "metrics": [
        {
         "field": "select field",
         "id": "1",
         "meta": {},
         "settings": { "size": 500 },
         "type": "raw_document"
        }
       ],
       "query": "POLICY_NAME:\"/Common/vs_staging_8000\"",
       "timeField": "@timestamp"
      }
     ]
    }
   ]
  }
 ]
}