{
 "title": "Website Availability Monitor",
 "time": { "from": "2018-08-05T16:00:00.000Z", "to": "2018-09-06T08:41:12.755Z" },
 "templating": {
  "list": [
   {
    "name": "URL",
    "query": "label_values(up{job=\"blackbox\"},instance)"
   }
  ]
 },
 "panels": [
  { "title": "Overall Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "UP status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }, "repeat": "URL" },
  {
   "title": "Current UP Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "up{instance=\"$URL\",type=\"URL\"}"
    }
   ]
  },
  {
   "title": "Service Status",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum_over_time(up{instance=\"$URL\",type=\"URL\"}[4w])/count_over_time(up{instance=\"$URL\",type=\"URL\"}[4w])"
    }
   ]
  },
  {
   "title": "Overall UP Status",
   "type": "graph",
   "gridPos": { "h": 9, "w": 19, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "up{instance=\"$URL\",type=\"URL\"}"
    }
   ]
  },
  { "title": "Availability Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 }, "repeat": "URL" },
  {
   "title": "Current Availability",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 16 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum_over_time(up{instance=\"$URL\",type=\"URL\"}[5m])/count_over_time(up{instance=\"$URL\",type=\"URL\"}[5m])"
    }
   ]
  },
  {
   "title": "Overall Availibily Status(2W)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 7, "y": 16 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum_over_time(up{instance=\"$URL\",type=\"URL\"}[2w])/count_over_time(up{instance=\"$URL\",type=\"URL\"}[2w])"
    }
   ]
  },
  {
   "title": "Overall Availibily Status(4W)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 12, "y": 16 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum_over_time(up{instance=\"$URL\",type=\"URL\"}[4w])/count_over_time(up{instance=\"$URL\",type=\"URL\"}[4w])"
    }
   ]
  },
  {
   "title": "Overall Availibily Status(8W)",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 16 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum_over_time(up{instance=\"$URL\",type=\"URL\"}[8w])/count_over_time(up{instance=\"$URL\",type=\"URL\"}[8w])"
    }
   ]
  },
  { "title": "Availability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 }, "repeat": "URL" },
  {
   "title": "Overall Avalibilty(2w)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(up{instance=\"$URL\",type=\"URL\"}[2w])/count_over_time(up{instance=\"$URL\",type=\"URL\"}[2w])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Overall Avalibilty(4w)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(up{instance=\"$URL\",type=\"URL\"}[4w])/count_over_time(up{instance=\"$URL\",type=\"URL\"}[4w])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Response Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 }, "repeat": "URL" },
  {
   "title": "Response Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{instance=\"$URL\"})",
     "legendFormat": "$URL"
    }
   ]
  }
 ]
}