- name: install security updates 
  yum:
      name: '*'
      security: yes
      state: latest
      update_cache: yes
  when: ansible_os_family == "RedHat"     

- name: install security updates on Suse
  zypper:
      name: '*'
      state: latest
      update_cache: yes
      type: patch
      extra_args: '--issue=security'
  when: ansible_os_family == "Suse"

       
#- name: get  CA cert of snfc.org domain
#  shell: openssl s_client -servername getcerts.snfc.org -connect getcerts.snfc.org:443 < /dev/null 2>/dev/null | openssl x509 -outform pem #>/etc/pki/ca-trust/source/anchors/snfcOrgCA.pem
#       
#- name: get  CA cert of snfc.org domain
#  shell: openssl s_client -servername getcerts.snfc.org -connect getcerts.snfc.org:443 < /dev/null 2>/dev/null | openssl x509 -outform pem #>/etc/ssl/certs/snfcOrgCA.pem
#
#- name: install the CA cert of snfc.org 
#  shell: update-ca-trust extract

