- name: enable firewalld
  systemd:
    name: firewalld
    state: started
    enabled: yes
  when: ansible_os_family == "Suse" 

- name: ensure cups is not installed
  package:
      name:  cups
      state: removed

- name: ensure auditd is installed
  package:
      name: audit
      state: installed


#- name: start auditd
#  systemd: 
#      name: auditd
#      state: restarted
#      enabled: yes
#      daemon_reload: yes

- name: create journald log dir
  file:
    path: /var/log/journal
    state: directory
    mode: 0755

- name: configure journald
  copy: 
    src: journald.conf 
    dest: /etc/systemd/journald.conf 
    mode: 0755 
    owner: root
  notify:
    restart_journald

