- name: install kibana
  package:
    name: "{{kibana_rpm_url}}"
    state: installed
  when: ansible_os_family == "Suse" or ansible_os_faminly == "RedHat"

- name: install kibana conf
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml

- name: check if x-pack is installed
  stat:
    path: /usr/share/kibana/plugins/x-pack
  register: xpack

- name: install x-pack plugin
  shell: /usr/share/kibana/bin/kibana-plugin install x-pack -q
  when:  xpack.stat.exists == false

- name: ensure /etc/kibana/certs is created
  file:
    path: /etc/kibana/certs
    state: directory
    
- name:   start kibana service
  systemd: 
    name: kibana
    state: restarted
    enabled: yes
    daemon_reload: yes