- name: Download jdk
  get_url:
    url: "{{JDK_URL}}"
    dest: /tmp/jdk-8u161-linux-x64.rpm
    headers: "{{JDK_HEADER}}"
    validate_certs: false

- name: install jdk 
  yum:
    name: /tmp/jdk-8u161-linux-x64.rpm
    state: present

- name: add JAVA_HOME 
  lineinfile: 
   dest: /etc/profile
   state: present
   regexp: '^export.*JAVA_HOME=.*'
   line:  "export JAVA_HOME=/usr/java/jdk1.8.0_161"




- name: Extract com.sap.prd.commonrepo.artifactdeployer.dist.cli-0.19.2.tar.gz into /opt
  unarchive:
    src: com.sap.prd.commonrepo.artifactdeployer.dist.cli-0.19.2.tar.gz
    dest: /opt



- name: Extract com.sap.prd.commonrepo.artifactimporter.dist.cli-0.11.5.tar.gz into /opt
  unarchive:
    src: com.sap.prd.commonrepo.artifactimporter.dist.cli-0.11.5.tar.gz
    dest: /opt/



- name: create  artifactimporter/artifactdeployer/nexus directory
  file:
    path: '{{ item }}'
    state: directory
  with_items:
    - /opt/artifactimporter
    - /opt/artifactdeployer
    - /opt/nexus


- name: copy artifactimporter files
  shell: rsync -a   /opt/artifactimporter-0.11.5/ /opt/artifactimporter/


- name: rename artifactdeployer
  shell: rsync -a /opt/artifactdeployer-0.19.2/ /opt/artifactdeployer/


- name: set ARTIFACTDEPLOYER_HOME
  lineinfile: 
   dest: /etc/profile
   state: present
   regexp: '^export.*ARTIFACTDEPLOYER_HOME=.*'
   line:  "export ARTIFACTDEPLOYER_HOME=/opt/artifactdeployer" 

- name: set ARTIFACTIMPORTER_HOME
  lineinfile: 
   dest: /etc/profile
   state: present
   regexp: '^export.*ARTIFACTIMPORTER_HOME=.*'
   line:  "export ARTIFACTIMPORTER_HOME=/opt/artifactimporter"    

- name: copy SAPCAR
  copy:
    src: SAPCAR
    dest: /usr/bin/SAPCAR
    mode: 0755
    owner: root
    group: root

- name: copy SAP_HANA_CLIENT100_122_10_Linux_on_x86_64.SAR
  copy:
    src: SAP_HANA_CLIENT100_122_10_Linux_on_x86_64.SAR
    dest: /opt/SAP_HANA_CLIENT100_122_10_Linux_on_x86_64.SAR 

- name: extract SAP_HANA_CLIENT100_122_10_Linux_on_x86_64.SAR
  shell: SAPCAR -xf SAP_HANA_CLIENT100_122_10_Linux_on_x86_64.SAR
  args:
    chdir: /opt/

- name: install hana client
  shell: /opt/SAP_HANA_CLIENT/hdbinst --batch -a client

- name: set HDBCLIENT_HOME
  lineinfile: 
   dest: /etc/profile
   state: present
   regexp: '^export.*HDBCLIENT_HOME=.*'
   line:  "export export HDBCLIENT_HOME=/usr/sap/hdbclient"    

  
- name: Download jenkins repo
  get_url:
    url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
    dest: /etc/yum.repos.d/jenkins.repo 

- name: import jenkins repo key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat-stable/jenkins.io.key

- name: install additional package
  yum: 
    name: "{{ item}}"
    state: latest
    update_cache: yes
  with_items:
    - libaio
    - git
    - jenkins

- name: download nexus
  get_url:
    url: http://download.sonatype.com/nexus/3/nexus-3.7.0-04-unix.tar.gz
    dest: /tmp/nexus-3.7.0-04-unix.tar.gz

- name: Extract nexus
  unarchive:
    src:  /tmp/nexus-3.7.0-04-unix.tar.gz
    dest: /opt
    remote_src: yes

- name: create nexus user
  user:
    name: nexus
    shell: /bin/sh
    home: /opt/nexus


- name: copy nexus 
  shell: rsync -a /opt/nexus-3.7.0-04/ /opt/nexus/


- name: set owner of /opt/nexus
  file:
    path: /opt/nexus
    owner: nexus
    group: nexus
    recurse: yes


   
   

- name: remove useless files
  file:  
    path: '{{ item }}'
    state: absent
  with_items:
    - /opt/nexus-3.7.0-04/
    - /tmp/nexus-3.7.0-04-unix.tar.gz
    - /tmp/jdk-8u161-linux-x64.rpm
    - /opt/SAP_HANA_CLIENT100_122_10_Linux_on_x86_64.SAR
    - /opt/artifactimporter-0.11.5/
    - /opt/artifactdeployer-0.19.2/ 

- name: set NEXUS_HOME
  lineinfile: 
   dest: /etc/profile
   state: present
   regexp: '^export.*NEXUS_HOME=.*'
   line:  "export NEXUS_HOME=/opt/nexus"    

- name: install nexus service file
  copy:
    src: nexus.service
    dest: /lib/systemd/system/nexus.service

- name: modify PATH 
  lineinfile: 
    dest: /etc/profile
    state: present
    regexp: '^export.*PATH=.*'
    line:  "export PATH=$PATH:$ARTIFACTDEPLOYER_HOME/bin:$ARTIFACTIMPORTER_HOME/bin:$HDBCLIENT_HOME:$NEXUS_HOME/bin:$JAVA_HOME/bin" 

- name: start nexus
  systemd:
    name: nexus
    state: restarted
    daemon_reload: yes
    enabled: yes

- name: ensure /tmp is global writable
  file: 
    path: /tmp
    state: directory
    mode: 0777


- name: start jenkins
  systemd:
    name: jenkins
    state: restarted
    daemon_reload: yes
    enabled: yes